// English for the server's Arabic messages, applied on the way out (route.ts) when the page asks for English. Messages are
// built from these sentences, so whole sentences are replaced wherever they appear; numbered ones go through the patterns.
const sentences: Record<string, string> = {
  'تصدير GoHighLevel يتطلب عمود البريد.': 'GoHighLevel export requires the email column.',
  'التصدير المخصص محدود بألف عميل. حدد العملاء أولًا.': 'Custom export is limited to 1,000 contacts. Select contacts first.',
  'إدارة العملاء غير مفعلة بعد.': 'CRM is not enabled yet.',
  'الحد الأقصى 100 جمهور محفوظ.': 'You can save up to 100 audiences.',
  'الحد الأقصى 100 قائمة.': 'You can create up to 100 lists.',
  'العميل غير موجود في حسابك.': 'This contact is not in your account.',
  'القائمة غير موجودة في حسابك.': 'This list is not in your account.',
  'العملية غير موجودة.': 'This action does not exist.',
  'طلب الحذف غير موجود أو عولج سابقًا.': 'This deletion request does not exist or was already handled.',

  'بلغت حد البحث اليومي لحسابك. يمكنك البحث مجددًا بعد 24 ساعة من أول بحث اليوم، أو تواصل مع مالك المنصة.': 'You have reached today’s search limit. You can search again 24 hours after today’s first search, or contact the platform owner.',
  'الحساب غير متاح أو تم تعطيله.': 'This account is unavailable or disabled.',
  'هذه العملية متاحة لمالك المنصة فقط.': 'Only the platform owner can do this.',
  'الرصيد المتاح لا يكفي لهذه العملية.': 'Not enough credits for this.',
  'البريد الإلكتروني أو كلمة المرور غير صحيحة.': 'Wrong email or password.',
  'سجّل الدخول للمتابعة.': 'Sign in to continue.',
  'انتهت جلستك. سجّل الدخول مجددًا.': 'Your session ended. Sign in again.',
  'طلبات كثيرة. انتظر دقيقة وحاول مجددًا.': 'Too many requests. Wait a minute and try again.',
  'معرّف الطلب مستخدم لبحث مختلف.': 'This request id belongs to a different search.',
  'الرصيد المتاح بعد حجز عمليات البحث لا يكفي.': 'Not enough credits left after your running searches.',
  'لديك بحث قيد التنفيذ. انتظر اكتماله.': 'You have a search running. Wait for it to finish.',
  'قائمة البحث ممتلئة مؤقتًا. حاول لاحقًا.': 'The search queue is full for now. Try later.',
  'البحث غير موجود في حسابك.': 'This search is not in your account.',
  'بعض النتائج غير موجودة في حسابك.': 'Some results are not in your account.',
  'لا توجد نتائج لتنزيلها.': 'Nothing to download.',
  'يوجد حساب بهذا البريد بالفعل.': 'An account with this email already exists.',
  'الدعوة غير صالحة أو انتهت مدتها.': 'This invitation is invalid or expired.',
  'الحساب موجود بالفعل. سجّل الدخول.': 'The account already exists. Sign in.',
  'المشترك غير موجود.': 'Member not found.',
  'ألغِ عمليات البحث الجارية أولًا قبل تعيين رصيد أقل من المحجوز.': 'Cancel the running searches before setting a balance below what they hold.',
  'كلمة المرور الحالية غير صحيحة.': 'The current password is wrong.',
  'رابط الاستعادة غير صالح أو انتهت مدته.': 'This recovery link is invalid or expired.',
  'البريد أو رمز الاسترجاع غير صحيح.': 'Wrong email or recovery code.',
  'تعذّر قراءة رصيد مزوّد البيانات. راجع بريد حساب المزوّد على الخادم.': 'Could not read the data provider’s credits. Check the provider account email on the server.',
  'قاعدة البيانات غير مهيأة على الخادم. تواصل مع مالك المنصة.': 'The database is not set up on the server. Contact the platform owner.',
  'جارٍ البحث والتحقق من الإيميلات.': 'Searching and verifying emails.',
  'لنتائج أكثر، وسّع المعايير: احذف حجم الشركة أو المدينة أو المسمى الوظيفي.': 'For more results, widen the search: remove the company size, the city or the job title.',
  'لنتائج أكثر، وسّع المعايير: احذف حجم الشركة أو المدينة أو أضف دولًا.': 'For more results, widen the search: remove the company size or the city, or add countries.',
  'لم نجد شركات جديدة مطابقة تعرض بريدها على موقعها حاليًا.': 'No new matching companies show an email on their website right now.',
  'لم نجد شركات جديدة مطابقة لها نطاق عمل صالح للبحث حاليًا.': 'No new matching companies have a usable business domain right now.',
  'دفعة بحث غير متجانسة. أعد المحاولة.': 'The search batch is inconsistent. Please retry.',
  'لا يوجد أشخاص جدد مطابقون لهذه المعايير حاليًا.': 'No new people match these filters right now.',
  'جرّبنا كل المطابقين المتاحين.': 'We have tried everyone available.',
  'تعذّرت قراءة نتائج دفعة مدفوعة؛ راجع حساب المزوّد.': 'A paid batch could not be read; check the provider account.',
  'نواصل قراءة مواقع الشركات المطابقة…': 'Still reading the matching companies’ websites…',
  'نواصل البحث عن بريد الشركات المطابقة…': 'Still finding email addresses for matching companies…',
  'نواصل البحث عن أشخاص مطابقين…': 'Still looking for matching people…',
  'حُسب فقط ما وصل.': 'You paid only for what arrived.',
  'تعذّر حفظ نتيجة الطلب. لن نعيد الإرسال تلقائيًا.': 'The result of the request could not be saved. It will not be sent again automatically.',
  'تعذّر إكمال البحث الآن. حاول مجددًا بعد قليل.': 'The search could not finish now. Try again shortly.',
  'توقف إرسال دفعة قبل تأكيده؛ راجع حساب المزوّد.': 'A batch stopped before it was confirmed; check the provider account.',
  'توقف إرسال الدفعة الأخيرة قبل تأكيده.': 'The last batch stopped before it was confirmed.',
  'توقف إرسال الطلب قبل تأكيده.': 'The request stopped before it was confirmed.',
  'نبحث عن الإيميلات ونتحقق منها. يمكنك العودة لاحقًا من سجل البحث.': 'Finding and verifying emails. You can come back later from your history.',
  'رصيد مزوّد البيانات نفد أثناء البحث؛ اشحن الرصيد.': 'The data provider ran out of credits during a search; top it up.',
  'رصيد مزوّد البيانات لا يكفي لإكمال البحث الآن.': 'The data provider’s credits are not enough to finish now.',
  'تواصل مع مالك المنصة.': 'Contact the platform owner.',
  'تعذّر إكمال قراءة النتائج من مزوّد البيانات.': 'The results could not be read from the data provider.',
  'تعذّر تحديث الحالة. سنحاول مجددًا؛ لن نعيد إرسال الطلب.': 'Could not update the status. We will retry without sending the request again.',
  'اكتب المدينة بالإنجليزية أو اختر مدينة رئيسية، أو اتركها فارغة.': 'Type the city in English, pick a main city, or leave it empty.',
  'اختر دولة واحدة عند تحديد المدينة.': 'Pick one country when you set a city.',
  'مزوّد البيانات غير مهيأ على الخادم.': 'The data provider is not set up on the server.',
  'انقطع الاتصال بمزوّد البيانات. حاول بعد قليل.': 'Lost the connection to the data provider. Try again shortly.',
  'مفتاح مزوّد البيانات غير صالح.': 'The data provider key is invalid.',
  'مزوّد البيانات مشغول حاليًا. حاول بعد دقيقة.': 'The data provider is busy. Try again in a minute.',
  'تعذّر طلب مزوّد البيانات. حاول بعد قليل.': 'The data provider request failed. Try again shortly.',
  'استجابة غير مقروءة من مزوّد البيانات.': 'Unreadable answer from the data provider.',
  'رفض مزوّد البيانات الطلب. راجع المعايير أو رصيد المزوّد.': 'The data provider refused the request. Check the filters or the provider’s credits.',
  'تغيّرت صيغة نتائج مزوّد البيانات. يلزم مراجعة الربط.': 'The data provider changed its result format; the integration needs a review.',
  'لم يصل رقم الطلب من مزوّد البيانات. لن نعيد الإرسال تلقائيًا.': 'No request id came back from the data provider. It will not be sent again automatically.',
  'الطلب أكبر من الحد المسموح.': 'The request is too large.',
  'تعذّر قراءة الطلب.': 'The request could not be read.',
  'وافق على شروط الاستخدام أولًا.': 'Accept the terms of use first.',
  'الفترة الزمنية غير صالحة.': 'Invalid time range.',
  'الصفحة المطلوبة غير موجودة.': 'Page not found.',
  'رصيدك صفر. تواصل مع مالك المنصة لإضافة رصيد قبل البحث.': 'Your balance is zero. Contact the platform owner for credits before searching.',
  'العملية المطلوبة غير موجودة.': 'Unknown action.',
  'راجع البيانات المدخلة، وتأكد من تأكيد معايير البحث.': 'Check what you entered, and confirm the search filters.',
  'راجع البيانات المدخلة.': 'Check what you entered.',
  'حدث خطأ غير متوقع. حاول مجددًا.': 'Something went wrong. Try again.',
  'إعداد عنوان المنصة (APP_URL) غير صالح.': 'The platform address (APP_URL) setting is invalid.',
  'هذا العنوان غير مسموح.': 'This address is not allowed.',
  'المعاينة المحلية فقط. إعداد الإنتاج غير مفعّل.': 'Local preview only. Production is not set up.',
  'مصدر الطلب غير مسموح.': 'Request origin not allowed.',
  'صيغة الطلب غير صحيحة.': 'Wrong request format.',
  'تعذّر فهم ما كتبته في «أخرى» الآن. اختر من القائمة أو حاول بعد قليل.': 'Could not understand what you typed under “Other” now. Pick from the list or try again shortly.',
  'خيار «أخرى» غير مفعّل حاليًا. اختر من القائمة.': '“Other” is not available right now. Pick from the list.',
  'المساعد غير متاح الآن. حاول بعد قليل.': 'The assistant is unavailable right now. Try again shortly.',
  'وصلت حد المساعد اليومي. حاول غدًا.': 'You have reached today’s assistant limit. Try again tomorrow.',
};
const patterns: [RegExp, (...m: string[]) => string][] = [
  [/بحثنا عن بريد (\d+) من الأشخاص المطابقين، ثم كمّلنا بإيميلات الشركات نفسها بعد فحص (\d+) منها، فوصلك (\d+) من (\d+)\./g,
    (_, p, c, d, r) => `We looked for the emails of ${p} matching people, then filled in with the companies’ own emails after verifying ${c} of them: you received ${d} of ${r}.`],
  [/بحثنا عن بريد (\d+) من الأشخاص المطابقين، ووجدنا بريدًا موثّقًا لـ (\d+) منهم(?:، منها (\d+) مكرر مستبعد)?\./g,
    (_, n, f, d) => `We looked for the emails of ${n} matching people and found a verified email for ${f}${d ? ` (${d} duplicates left out)` : ''}.`],
  [/بحثنا عن بريد (\d+) من الأشخاص المطابقين، ولم نجد بريدًا موثّقًا لأيّ منهم\./g, (_, n) => `We looked for the emails of ${n} matching people and found no verified email.`],
  [/تحققنا من بريد (\d+) من الشركات المطابقة، وصحّ بريد (\d+) منها(?:، منها (\d+) مكرر مستبعد)?\./g,
    (_, n, f, d) => `We verified the emails of ${n} matching companies; ${f} passed${d ? ` (${d} duplicates left out)` : ''}.`],
  [/تحققنا من بريد (\d+) من الشركات المطابقة، ولم يصح أيّ منها\./g, (_, n) => `We verified the emails of ${n} matching companies; none passed.`],
  [/أعد البحث بالمعايير نفسها لتجربة (شركات أخرى|أشخاص آخرين)، أو وسّعها لنتائج أكثر\./g,
    (_, who) => `Search again with the same filters to try ${who === 'شركات أخرى' ? 'other companies' : 'other people'}, or widen them for more results.`],
  [/لم نجد مجالًا مهنيًا يطابق «(.+?)»\. جرّب كلمات أوضح أو اختر من القائمة\./g, (_, w) => `No business field matches “${w}”. Try clearer words or pick from the list.`],
];
const ordered = Object.keys(sentences).sort((a, b) => b.length - a.length); // longest first: a sentence may contain a shorter one
export function english(text: string) {
  let out = text;
  for (const [re, to] of patterns) out = out.replace(re, (...m) => to(...m.slice(0, -2) as string[]));
  for (const ar of ordered) if (out.includes(ar)) out = out.split(ar).join(sentences[ar]);
  return out;
}
// The fields a page shows to the member: errors and search messages, anywhere in the answer.
export function englishBody(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(englishBody);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, (k === 'error' || k === 'message') && typeof v === 'string' ? english(v) : englishBody(v)]));
}
