import { fieldOf } from './contracts';
import { norm } from './places';
import { searchWords } from './niches';

// Every provider category (src/lib/industries.ts lists the keys) and the Arabic name members see for it.
export const INDUSTRY_AR: Record<string, string> = {
  "Abrasives and Nonmetallic Minerals Manufacturing": "تصنيع المواد الكاشطة والمعادن اللافلزية",
  "Accessible Architecture and Design": "العمارة والتصميم الميسّر للجميع",
  "Accessible Hardware Manufacturing": "تصنيع الأجهزة الميسّرة لذوي الإعاقة",
  "Accommodation and Food Services": "خدمات الإقامة والطعام",
  "Accounting": "المحاسبة والمراجعة",
  "Administration of Justice": "إدارة العدالة",
  "Administrative and Support Services": "الخدمات الإدارية والمساندة",
  "Advertising Services": "خدمات الدعاية والإعلان",
  "Agricultural Chemical Manufacturing": "تصنيع الكيماويات الزراعية",
  "Agriculture": "الزراعة",
  "Agriculture, Construction, Mining Machinery Manufacturing": "تصنيع آلات الزراعة والبناء والتعدين",
  "Air, Water, and Waste Program Management": "إدارة برامج الهواء والمياه والنفايات",
  "Airlines and Aviation": "شركات الطيران",
  "Alternative Dispute Resolution": "تسوية النزاعات بالتحكيم والوساطة",
  "Alternative Fuel Vehicle Manufacturing": "تصنيع مركبات الوقود البديل",
  "Alternative Medicine": "الطب البديل",
  "Ambulance Services": "خدمات الإسعاف",
  "Amusement Parks and Arcades": "مدن الألعاب وصالات الترفيه",
  "Animal Feed Manufacturing": "تصنيع أعلاف الحيوانات",
  "Animation": "الرسوم المتحركة",
  "Animation and Post-production": "الرسوم المتحركة والمونتاج",
  "Apparel & Fashion": "الأزياء والملابس",
  "Apparel Manufacturing": "مصانع الملابس",
  "Appliances, Electrical, and Electronics Manufacturing": "تصنيع الأجهزة الكهربائية والإلكترونية",
  "Architectural and Structural Metal Manufacturing": "تصنيع المعادن الإنشائية والمعمارية",
  "Architecture and Planning": "الهندسة المعمارية والتخطيط",
  "Armed Forces": "القوات المسلحة",
  "Artificial Rubber and Synthetic Fiber Manufacturing": "تصنيع المطاط الصناعي والألياف الاصطناعية",
  "Artists and Writers": "الفنانون والكتّاب",
  "Arts & Crafts": "الفنون والحرف اليدوية",
  "Audio and Video Equipment Manufacturing": "تصنيع معدات الصوت والفيديو",
  "Automation Machinery Manufacturing": "تصنيع آلات الأتمتة",
  "Automotive": "قطاع السيارات",
  "Aviation & Aerospace": "الطيران وصناعات الفضاء",
  "Aviation and Aerospace Component Manufacturing": "تصنيع مكونات الطائرات والمركبات الفضائية",
  "Baked Goods Manufacturing": "مصانع المخبوزات",
  "Banking": "البنوك",
  "Bed-and-Breakfasts, Hostels, Homestays": "بيوت الضيافة والنزل الصغيرة",
  "Beverage Manufacturing": "مصانع المشروبات",
  "Biomass Electric Power Generation": "توليد الكهرباء من الكتلة الحيوية",
  "Biotechnology": "التقنية الحيوية",
  "Biotechnology Research": "أبحاث التقنية الحيوية",
  "Blockchain Services": "خدمات البلوك تشين",
  "Blogs": "المدونات",
  "Boilers, Tanks, and Shipping Container Manufacturing": "تصنيع المراجل والخزانات وحاويات الشحن",
  "Book and Periodical Publishing": "نشر الكتب والدوريات",
  "Book Publishing": "دور نشر الكتب",
  "Broadcast Media Production and Distribution": "إنتاج وتوزيع المحتوى الإذاعي والتلفزيوني",
  "Building Construction": "مقاولات المباني",
  "Building Equipment Contractors": "مقاولو معدات المباني",
  "Building Finishing Contractors": "مقاولو تشطيب المباني",
  "Building Materials": "مواد البناء",
  "Building Structure and Exterior Contractors": "مقاولو الهياكل والواجهات الخارجية",
  "Business Consulting and Services": "الاستشارات والخدمات للأعمال",
  "Business Content": "المحتوى التجاري",
  "Business Intelligence Platforms": "منصات ذكاء الأعمال",
  "Business Supplies & Equipment": "مستلزمات ومعدات الأعمال",
  "Cable and Satellite Programming": "برامج الكيبل والقنوات الفضائية",
  "Capital Markets": "أسواق المال",
  "Caterers": "شركات الضيافة والتموين",
  "Chemical Manufacturing": "مصانع الكيماويات",
  "Chemical Raw Materials Manufacturing": "تصنيع المواد الكيميائية الخام",
  "Child Day Care Services": "حضانات الأطفال",
  "Chiropractors": "أخصائيو العلاج اليدوي للعمود الفقري",
  "Circuses and Magic Shows": "السيرك وعروض السحر",
  "Civic and Social Organizations": "الجمعيات المدنية والاجتماعية",
  "Civil Engineering": "الهندسة المدنية",
  "Claims Adjusting, Actuarial Services": "تسوية المطالبات والخدمات الإكتوارية",
  "Clay and Refractory Products Manufacturing": "تصنيع منتجات الطين والحراريات",
  "Climate Data and Analytics": "بيانات وتحليلات المناخ",
  "Climate Technology Product Manufacturing": "تصنيع منتجات تقنيات المناخ",
  "Coal Mining": "تعدين الفحم",
  "Collection Agencies": "شركات تحصيل الديون",
  "Commercial and Industrial Equipment Rental": "تأجير المعدات التجارية والصناعية",
  "Commercial and Industrial Machinery Maintenance": "صيانة الآلات التجارية والصناعية",
  "Commercial and Service Industry Machinery Manufacturing": "تصنيع آلات القطاعين التجاري والخدمي",
  "Commercial Real Estate": "العقارات التجارية",
  "Communications Equipment Manufacturing": "تصنيع معدات الاتصالات",
  "Community Development and Urban Planning": "التنمية المجتمعية والتخطيط العمراني",
  "Community Services": "الخدمات المجتمعية",
  "Computer and Network Security": "أمن الحاسب والشبكات",
  "Computer Games": "ألعاب الحاسب",
  "Computer Hardware": "أجهزة الحاسب",
  "Computer Hardware Manufacturing": "تصنيع أجهزة الحاسب",
  "Computer Networking": "شبكات الحاسب",
  "Computer Networking Products": "منتجات شبكات الحاسب",
  "Computers and Electronics Manufacturing": "تصنيع الحواسيب والإلكترونيات",
  "Conservation Programs": "برامج حماية البيئة والموارد",
  "Construction": "قطاع الإنشاءات",
  "Construction Hardware Manufacturing": "تصنيع أدوات ومعدات البناء",
  "Consumer Electronics": "الإلكترونيات الاستهلاكية",
  "Consumer Goods": "السلع الاستهلاكية",
  "Consumer Goods Rental": "تأجير السلع الاستهلاكية",
  "Consumer Services": "خدمات المستهلكين",
  "Correctional Institutions": "المؤسسات الإصلاحية",
  "Cosmetics": "مستحضرات التجميل",
  "Cosmetology and Barber Schools": "معاهد التجميل والحلاقة",
  "Courts of Law": "المحاكم",
  "Credit Intermediation": "الوساطة الائتمانية",
  "Cutlery and Handtool Manufacturing": "تصنيع السكاكين والأدوات اليدوية",
  "Dairy": "قطاع الألبان",
  "Dairy Product Manufacturing": "مصانع منتجات الألبان",
  "Dance Companies": "فرق الرقص",
  "Data Infrastructure and Analytics": "البنية التحتية للبيانات وتحليلها",
  "Data Security Software Products": "برمجيات أمن البيانات",
  "Defense & Space": "الدفاع والفضاء",
  "Defense and Space Manufacturing": "التصنيع الدفاعي والفضائي",
  "Dentists": "أطباء الأسنان",
  "Design": "التصميم",
  "Design Services": "خدمات التصميم",
  "Desktop Computing Software Products": "برمجيات الحاسب المكتبي",
  "Digital Accessibility Services": "خدمات إتاحة المحتوى الرقمي",
  "E-learning": "التعلم الإلكتروني",
  "E-Learning Providers": "مزودو التعليم عن بعد",
  "Economic Programs": "البرامج الاقتصادية",
  "Education": "التعليم",
  "Education Administration Programs": "برامج الإدارة التعليمية",
  "Education Management": "إدارة المؤسسات التعليمية",
  "Electric Lighting Equipment Manufacturing": "تصنيع معدات الإضاءة الكهربائية",
  "Electric Power Generation": "توليد الطاقة الكهربائية",
  "Electric Power Transmission, Control, and Distribution": "نقل وتوزيع الكهرباء والتحكم بها",
  "Electrical Equipment Manufacturing": "تصنيع المعدات الكهربائية",
  "Electronic and Precision Equipment Maintenance": "صيانة الأجهزة الإلكترونية والدقيقة",
  "Embedded Software Products": "البرمجيات المدمجة",
  "Emergency and Relief Services": "خدمات الطوارئ والإغاثة",
  "Engineering Services": "الخدمات الهندسية",
  "Engines and Power Transmission Equipment Manufacturing": "تصنيع المحركات ومعدات نقل الحركة",
  "Entertainment": "الترفيه",
  "Entertainment Providers": "مقدمو خدمات الترفيه",
  "Environmental Quality Programs": "برامج جودة البيئة",
  "Environmental Services": "الخدمات البيئية",
  "Equipment Rental Services": "خدمات تأجير المعدات",
  "Events Services": "خدمات الفعاليات والمناسبات",
  "Executive Offices": "المكاتب التنفيذية العليا",
  "Executive Search Services": "خدمات استقطاب كبار التنفيذيين",
  "Fabricated Metal Products": "المنتجات المعدنية المصنّعة",
  "Facilities Services": "خدمات إدارة المرافق",
  "Family Planning Centers": "مراكز تنظيم الأسرة",
  "Farming": "المزارع",
  "Farming, Ranching, Forestry": "الزراعة وتربية المواشي والغابات",
  "Fashion Accessories Manufacturing": "تصنيع إكسسوارات الأزياء",
  "Financial Services": "الخدمات المالية",
  "Fine Art": "الفنون الجميلة",
  "Fine Arts Schools": "مدارس الفنون الجميلة",
  "Fire Protection": "الحماية من الحرائق",
  "Fisheries": "مصائد الأسماك",
  "Flight Training": "التدريب على الطيران",
  "Food & Beverages": "الأغذية والمشروبات",
  "Food and Beverage Manufacturing": "تصنيع الأغذية والمشروبات",
  "Food and Beverage Retail": "بيع الأغذية والمشروبات بالتجزئة",
  "Food and Beverage Services": "خدمات الأغذية والمشروبات",
  "Food Production": "إنتاج الأغذية",
  "Footwear and Leather Goods Repair": "إصلاح الأحذية والمنتجات الجلدية",
  "Footwear Manufacturing": "مصانع الأحذية",
  "Forestry and Logging": "الغابات وقطع الأخشاب",
  "Fossil Fuel Electric Power Generation": "توليد الكهرباء بالوقود الأحفوري",
  "Freight and Package Transportation": "شحن البضائع والطرود",
  "Fruit and Vegetable Preserves Manufacturing": "تصنيع حفظ الفواكه والخضروات",
  "Fuel Cell Manufacturing": "تصنيع خلايا الوقود",
  "Fundraising": "جمع التبرعات",
  "Funds and Trusts": "الصناديق والأمانات",
  "Furniture": "الأثاث",
  "Furniture and Home Furnishings Manufacturing": "تصنيع الأثاث والمفروشات المنزلية",
  "Geothermal Electric Power Generation": "توليد الكهرباء من الطاقة الحرارية الأرضية",
  "Glass Product Manufacturing": "تصنيع منتجات الزجاج",
  "Glass, Ceramics and Concrete Manufacturing": "تصنيع الزجاج والسيراميك والخرسانة",
  "Golf Courses and Country Clubs": "ملاعب الجولف والنوادي الريفية",
  "Government Administration": "الإدارة الحكومية",
  "Government Relations": "العلاقات الحكومية",
  "Government Relations Services": "خدمات العلاقات الحكومية",
  "Graphic Design": "التصميم الجرافيكي",
  "Ground Passenger Transportation": "نقل الركاب البري",
  "Health and Human Services": "الخدمات الصحية والإنسانية",
  "Health, Wellness & Fitness": "الصحة والعافية واللياقة",
  "Higher Education": "التعليم العالي",
  "Highway, Street, and Bridge Construction": "إنشاء الطرق والجسور",
  "Historical Sites": "المواقع التاريخية",
  "Holding Companies": "الشركات القابضة",
  "Home Health Care Services": "الرعاية الصحية المنزلية",
  "Horticulture": "البستنة",
  "Hospitality": "قطاع الضيافة",
  "Hospitals": "المستشفيات",
  "Hospitals and Health Care": "المستشفيات والرعاية الصحية",
  "Hotels and Motels": "الفنادق والنُزل",
  "Household and Institutional Furniture Manufacturing": "تصنيع أثاث المنازل والمؤسسات",
  "Household Appliance Manufacturing": "تصنيع الأجهزة المنزلية",
  "Household Services": "الخدمات المنزلية",
  "Housing and Community Development": "الإسكان والتنمية المجتمعية",
  "Housing Programs": "برامج الإسكان",
  "Human Resources": "الموارد البشرية",
  "Human Resources Services": "خدمات الموارد البشرية",
  "HVAC and Refrigeration Equipment Manufacturing": "تصنيع معدات التكييف والتبريد",
  "Hydroelectric Power Generation": "توليد الكهرباء من المياه",
  "Import & Export": "الاستيراد والتصدير",
  "Individual and Family Services": "خدمات الأفراد والأسر",
  "Industrial Automation": "الأتمتة الصناعية",
  "Industrial Machinery Manufacturing": "تصنيع الآلات الصناعية",
  "Industry Associations": "الاتحادات والجمعيات الصناعية",
  "Information Services": "خدمات المعلومات",
  "Information Technology & Services": "تقنية المعلومات وخدماتها",
  "Insurance": "التأمين",
  "Insurance Agencies and Brokerages": "وكالات ووسطاء التأمين",
  "Insurance and Employee Benefit Funds": "صناديق التأمين ومزايا الموظفين",
  "Insurance Carriers": "شركات التأمين",
  "Interior Design": "التصميم الداخلي",
  "International Affairs": "الشؤون الدولية",
  "International Trade and Development": "التجارة والتنمية الدولية",
  "Internet Marketplace Platforms": "منصات الأسواق الإلكترونية",
  "Internet News": "الأخبار الإلكترونية",
  "Internet Publishing": "النشر الإلكتروني",
  "Interurban and Rural Bus Services": "حافلات النقل بين المدن والأرياف",
  "Investment Advice": "الاستشارات الاستثمارية",
  "Investment Banking": "الخدمات المصرفية الاستثمارية",
  "Investment Management": "إدارة الاستثمار",
  "IT Services and IT Consulting": "خدمات واستشارات تقنية المعلومات",
  "IT System Custom Software Development": "تطوير البرمجيات المخصصة للأنظمة",
  "IT System Data Services": "خدمات بيانات الأنظمة التقنية",
  "IT System Design Services": "خدمات تصميم الأنظمة التقنية",
  "IT System Installation and Disposal": "تركيب الأنظمة التقنية والتخلص منها",
  "IT System Operations and Maintenance": "تشغيل وصيانة الأنظمة التقنية",
  "IT System Testing and Evaluation": "اختبار وتقييم الأنظمة التقنية",
  "IT System Training and Support": "تدريب ودعم الأنظمة التقنية",
  "Janitorial Services": "خدمات النظافة",
  "Landscaping Services": "خدمات تنسيق الحدائق",
  "Language Schools": "معاهد اللغات",
  "Laundry and Drycleaning Services": "المغاسل والتنظيف الجاف",
  "Law Enforcement": "إنفاذ القانون",
  "Law Practice": "مكاتب المحاماة",
  "Leasing Non-residential Real Estate": "تأجير العقارات غير السكنية",
  "Leasing Residential Real Estate": "تأجير العقارات السكنية",
  "Leather Product Manufacturing": "تصنيع المنتجات الجلدية",
  "Legal Services": "الخدمات القانونية",
  "Legislative Offices": "الجهات التشريعية",
  "Leisure, Travel & Tourism": "السياحة والسفر والترفيه",
  "Libraries": "المكتبات",
  "Lime and Gypsum Products Manufacturing": "تصنيع منتجات الجير والجبس",
  "Loan Brokers": "وسطاء القروض",
  "Luxury Goods & Jewelry": "السلع الفاخرة والمجوهرات",
  "Machinery Manufacturing": "تصنيع الآلات",
  "Magnetic and Optical Media Manufacturing": "تصنيع الوسائط المغناطيسية والضوئية",
  "Manufacturing": "التصنيع",
  "Maritime": "قطاع الملاحة البحرية",
  "Maritime Transportation": "النقل البحري",
  "Market Research": "أبحاث السوق",
  "Marketing Services": "خدمات التسويق",
  "Mattress and Blinds Manufacturing": "تصنيع الفرشات والستائر",
  "Measuring and Control Instrument Manufacturing": "تصنيع أجهزة القياس والتحكم",
  "Meat Products Manufacturing": "مصانع منتجات اللحوم",
  "Mechanical Or Industrial Engineering": "الهندسة الميكانيكية والصناعية",
  "Media and Telecommunications": "الإعلام والاتصالات",
  "Media Production": "الإنتاج الإعلامي",
  "Medical and Diagnostic Laboratories": "المختبرات الطبية والتشخيصية",
  "Medical Device": "الأجهزة الطبية",
  "Medical Equipment Manufacturing": "تصنيع المعدات الطبية",
  "Medical Practices": "العيادات الطبية",
  "Mental Health Care": "رعاية الصحة النفسية",
  "Metal Ore Mining": "تعدين خامات المعادن",
  "Metal Treatments": "معالجة المعادن",
  "Metal Valve, Ball, and Roller Manufacturing": "تصنيع الصمامات والكرات والبكرات المعدنية",
  "Metalworking Machinery Manufacturing": "تصنيع آلات تشغيل المعادن",
  "Military and International Affairs": "الشؤون العسكرية والدولية",
  "Mining": "التعدين",
  "Mobile Computing Software Products": "برمجيات الأجهزة المحمولة",
  "Mobile Food Services": "عربات الطعام المتنقلة",
  "Mobile Gaming Apps": "تطبيقات ألعاب الجوال",
  "Motor Vehicle Manufacturing": "تصنيع المركبات",
  "Motor Vehicle Parts Manufacturing": "تصنيع قطع غيار المركبات",
  "Movies and Sound Recording": "الأفلام والتسجيل الصوتي",
  "Movies, Videos, and Sound": "الأفلام والفيديو والصوتيات",
  "Museums": "المتاحف",
  "Museums, Historical Sites, and Zoos": "المتاحف والمواقع التاريخية وحدائق الحيوان",
  "Music": "الموسيقى",
  "Musicians": "الموسيقيون",
  "Nanotechnology Research": "أبحاث تقنية النانو",
  "Natural Gas Distribution": "توزيع الغاز الطبيعي",
  "Natural Gas Extraction": "استخراج الغاز الطبيعي",
  "Newspaper Publishing": "الصحف",
  "Non-profit Organization Management": "إدارة المنظمات غير الربحية",
  "Non-profit Organizations": "المنظمات غير الربحية",
  "Nonmetallic Mineral Mining": "تعدين المعادن اللافلزية",
  "Nonresidential Building Construction": "إنشاء المباني غير السكنية",
  "Nuclear Electric Power Generation": "توليد الكهرباء النووية",
  "Nursing Homes and Residential Care Facilities": "دور الرعاية والتمريض",
  "Office Administration": "الإدارة المكتبية",
  "Office Furniture and Fixtures Manufacturing": "تصنيع الأثاث والتجهيزات المكتبية",
  "Oil and Coal Product Manufacturing": "تصنيع منتجات النفط والفحم",
  "Oil and Gas": "النفط والغاز",
  "Oil Extraction": "استخراج النفط",
  "Oil, Gas, and Mining": "النفط والغاز والتعدين",
  "Online and Mail Order Retail": "التجزئة الإلكترونية والطلب بالبريد",
  "Online Audio and Video Media": "الوسائط الصوتية والمرئية عبر الإنترنت",
  "Online Media": "الإعلام الإلكتروني",
  "Operations Consulting": "استشارات العمليات التشغيلية",
  "Optometrists": "أخصائيو البصريات",
  "Outpatient Care Centers": "مراكز الرعاية الخارجية",
  "Outsourcing and Offshoring Consulting": "استشارات الاستعانة بمصادر خارجية",
  "Outsourcing/Offshoring": "الاستعانة بمصادر خارجية",
  "Packaging & Containers": "التغليف والحاويات",
  "Packaging and Containers Manufacturing": "تصنيع مواد التغليف والحاويات",
  "Paint, Coating, and Adhesive Manufacturing": "تصنيع الدهانات والطلاء واللواصق",
  "Paper & Forest Products": "الورق والمنتجات الحرجية",
  "Paper and Forest Product Manufacturing": "تصنيع الورق والمنتجات الحرجية",
  "Pension Funds": "صناديق التقاعد",
  "Performing Arts": "الفنون الأدائية",
  "Performing Arts and Spectator Sports": "الفنون الأدائية والرياضات الجماهيرية",
  "Periodical Publishing": "نشر المجلات والدوريات",
  "Personal and Laundry Services": "الخدمات الشخصية والمغاسل",
  "Personal Care Product Manufacturing": "تصنيع منتجات العناية الشخصية",
  "Personal Care Services": "خدمات العناية الشخصية",
  "Pet Services": "خدمات الحيوانات الأليفة",
  "Pharmaceutical Manufacturing": "مصانع الأدوية",
  "Philanthropic Fundraising Services": "خدمات جمع التبرعات الخيرية",
  "Philanthropy": "العمل الخيري",
  "Photography": "التصوير الفوتوغرافي",
  "Physical, Occupational and Speech Therapists": "أخصائيو العلاج الطبيعي والوظيفي والنطق",
  "Physicians": "الأطباء",
  "Pipeline Transportation": "النقل عبر خطوط الأنابيب",
  "Plastics and Rubber Product Manufacturing": "تصنيع منتجات البلاستيك والمطاط",
  "Plastics Manufacturing": "مصانع البلاستيك",
  "Political Organizations": "المنظمات السياسية",
  "Postal Services": "خدمات البريد",
  "Primary and Secondary Education": "التعليم الابتدائي والثانوي",
  "Primary Metal Manufacturing": "تصنيع المعادن الأساسية",
  "Printing Services": "خدمات الطباعة",
  "Professional Organizations": "الهيئات والجمعيات المهنية",
  "Professional Services": "الخدمات المهنية",
  "Professional Training and Coaching": "التدريب المهني والتطوير الشخصي",
  "Program Development": "تطوير البرامج والمبادرات",
  "Public Assistance Programs": "برامج المساعدات العامة",
  "Public Health": "الصحة العامة",
  "Public Policy": "السياسات العامة",
  "Public Policy Offices": "مكاتب السياسات العامة",
  "Public Relations and Communications Services": "العلاقات العامة وخدمات الاتصال",
  "Public Safety": "السلامة العامة",
  "Racetracks": "مضامير السباق",
  "Radio and Television Broadcasting": "البث الإذاعي والتلفزيوني",
  "Rail Transportation": "النقل بالسكك الحديدية",
  "Railroad Equipment Manufacturing": "تصنيع معدات السكك الحديدية",
  "Ranching": "مزارع تربية المواشي",
  "Ranching and Fisheries": "تربية المواشي والأسماك",
  "Real Estate": "العقارات",
  "Real Estate Agents and Brokers": "الوكلاء والوسطاء العقاريون",
  "Real Estate and Equipment Rental Services": "تأجير العقارات والمعدات",
  "Recreational Facilities": "المرافق الترفيهية",
  "Regenerative Design": "التصميم المتجدد",
  "Religious Institutions": "المؤسسات الدينية",
  "Renewable Energy Equipment Manufacturing": "تصنيع معدات الطاقة المتجددة",
  "Renewable Energy Power Generation": "توليد الطاقة المتجددة",
  "Renewable Energy Semiconductor Manufacturing": "تصنيع أشباه موصلات الطاقة المتجددة",
  "Renewables & Environment": "الطاقة المتجددة والبيئة",
  "Repair and Maintenance": "الإصلاح والصيانة",
  "Research": "البحث العلمي",
  "Research Services": "خدمات البحوث",
  "Residential Building Construction": "إنشاء المباني السكنية",
  "Restaurants": "المطاعم",
  "Retail": "تجارة التجزئة",
  "Retail Apparel and Fashion": "محلات الملابس والأزياء",
  "Retail Appliances, Electrical, and Electronic Equipment": "محلات الأجهزة الكهربائية والإلكترونية",
  "Retail Art Dealers": "تجار الأعمال الفنية",
  "Retail Art Supplies": "محلات مستلزمات الفنون",
  "Retail Books and Printed News": "المكتبات ومحلات الصحف",
  "Retail Building Materials and Garden Equipment": "محلات مواد البناء ومعدات الحدائق",
  "Retail Florists": "محلات الورود",
  "Retail Furniture and Home Furnishings": "معارض الأثاث والمفروشات",
  "Retail Gasoline": "محطات الوقود",
  "Retail Groceries": "محلات البقالة",
  "Retail Health and Personal Care Products": "محلات منتجات الصحة والعناية الشخصية",
  "Retail Luxury Goods and Jewelry": "محلات السلع الفاخرة والمجوهرات",
  "Retail Motor Vehicles": "معارض السيارات",
  "Retail Musical Instruments": "محلات الآلات الموسيقية",
  "Retail Office Equipment": "محلات المعدات المكتبية",
  "Retail Office Supplies and Gifts": "محلات القرطاسية والهدايا",
  "Retail Pharmacies": "الصيدليات",
  "Retail Recyclable Materials & Used Merchandise": "محلات المواد المعاد تدويرها والمستعملة",
  "Reupholstery and Furniture Repair": "تنجيد وإصلاح الأثاث",
  "Robot Manufacturing": "تصنيع الروبوتات",
  "Robotics Engineering": "هندسة الروبوتات",
  "Rubber Products Manufacturing": "تصنيع منتجات المطاط",
  "Satellite Telecommunications": "الاتصالات الفضائية",
  "Savings Institutions": "مؤسسات الادخار",
  "School and Employee Bus Services": "حافلات المدارس والموظفين",
  "Seafood Product Manufacturing": "مصانع المأكولات البحرية",
  "Secretarial Schools": "معاهد السكرتارية",
  "Securities and Commodity Exchanges": "بورصات الأوراق المالية والسلع",
  "Security and Investigations": "الأمن والتحقيقات",
  "Security Guards and Patrol Services": "حراس الأمن وخدمات الدوريات",
  "Security Systems Services": "خدمات أنظمة الأمن",
  "Semiconductor Manufacturing": "تصنيع أشباه الموصلات",
  "Semiconductors": "أشباه الموصلات",
  "Services for Renewable Energy": "خدمات الطاقة المتجددة",
  "Services for the Elderly and Disabled": "خدمات كبار السن وذوي الإعاقة",
  "Sheet Music Publishing": "نشر النوتات الموسيقية",
  "Shipbuilding": "بناء السفن",
  "Shuttles and Special Needs Transportation Services": "النقل المخصص وخدمات المواصلات الخاصة",
  "Sightseeing Transportation": "النقل السياحي",
  "Skiing Facilities": "منتجعات التزلج",
  "Smart Meter Manufacturing": "تصنيع العدادات الذكية",
  "Soap and Cleaning Product Manufacturing": "تصنيع الصابون ومنتجات التنظيف",
  "Social Networking Platforms": "منصات التواصل الاجتماعي",
  "Software Development": "تطوير البرمجيات",
  "Solar Electric Power Generation": "توليد الكهرباء بالطاقة الشمسية",
  "Sound Recording": "التسجيل الصوتي",
  "Space Research and Technology": "أبحاث وتقنيات الفضاء",
  "Specialty Trade Contractors": "مقاولو الأعمال التخصصية",
  "Spectator Sports": "الرياضات الجماهيرية",
  "Sporting Goods": "الأدوات الرياضية",
  "Sporting Goods Manufacturing": "تصنيع الأدوات الرياضية",
  "Sports and Recreation Instruction": "التدريب الرياضي والترفيهي",
  "Sports Teams and Clubs": "الفرق والأندية الرياضية",
  "Spring and Wire Product Manufacturing": "تصنيع النوابض والأسلاك",
  "Staffing and Recruiting": "التوظيف والاستقطاب",
  "Steam and Air-Conditioning Supply": "إمدادات البخار والتكييف",
  "Strategic Management Services": "خدمات الإدارة الاستراتيجية",
  "Subdivision of Land": "تقسيم الأراضي",
  "Sugar and Confectionery Product Manufacturing": "تصنيع السكر والحلويات",
  "Surveying and Mapping Services": "خدمات المساحة والخرائط",
  "Taxi and Limousine Services": "خدمات التاكسي والليموزين",
  "Technical and Vocational Training": "التدريب التقني والمهني",
  "Technology, Information and Internet": "التقنية والمعلومات والإنترنت",
  "Technology, Information and Media": "التقنية والمعلومات والإعلام",
  "Telecommunications": "الاتصالات",
  "Telecommunications Carriers": "مشغلو الاتصالات",
  "Telephone Call Centers": "مراكز الاتصال الهاتفي",
  "Temporary Help Services": "خدمات العمالة المؤقتة",
  "Textile Manufacturing": "مصانع النسيج",
  "Theater Companies": "فرق المسرح",
  "Think Tanks": "مراكز الفكر والدراسات",
  "Tobacco": "قطاع التبغ",
  "Tobacco Manufacturing": "مصانع التبغ",
  "Translation and Localization": "الترجمة والتوطين",
  "Transportation Equipment Manufacturing": "تصنيع معدات النقل",
  "Transportation Programs": "برامج النقل",
  "Transportation, Logistics, Supply Chain and Storage": "النقل والخدمات اللوجستية وسلاسل الإمداد",
  "Transportation/Trucking/Railroad": "النقل بالشاحنات والسكك الحديدية",
  "Travel Arrangements": "ترتيبات السفر",
  "Truck Transportation": "النقل بالشاحنات",
  "Trusts and Estates": "الأمانات والتركات",
  "Turned Products and Fastener Manufacturing": "تصنيع المخروطات والمثبتات",
  "Urban Transit Services": "خدمات النقل الحضري",
  "Utilities": "المرافق العامة",
  "Utilities Administration": "إدارة المرافق العامة",
  "Utility System Construction": "إنشاء شبكات المرافق",
  "Vehicle Repair and Maintenance": "إصلاح وصيانة المركبات",
  "Venture Capital and Private Equity Principals": "رأس المال الجريء والأسهم الخاصة",
  "Veterinary": "الطب البيطري",
  "Veterinary Services": "الخدمات البيطرية",
  "Vocational Rehabilitation Services": "خدمات التأهيل المهني",
  "Warehousing": "المستودعات",
  "Warehousing and Storage": "المستودعات والتخزين",
  "Waste Collection": "جمع النفايات",
  "Waste Treatment and Disposal": "معالجة النفايات والتخلص منها",
  "Water Supply and Irrigation Systems": "إمدادات المياه وأنظمة الري",
  "Water, Waste, Steam, and Air Conditioning Services": "خدمات المياه والنفايات والبخار والتكييف",
  "Wellness and Fitness Services": "خدمات العافية واللياقة",
  "Wholesale": "تجارة الجملة",
  "Wholesale Apparel and Sewing Supplies": "جملة الملابس ومستلزمات الخياطة",
  "Wholesale Appliances, Electrical, and Electronics": "جملة الأجهزة الكهربائية والإلكترونية",
  "Wholesale Building Materials": "جملة مواد البناء",
  "Wholesale Chemical and Allied Products": "جملة الكيماويات والمنتجات المرتبطة",
  "Wholesale Computer Equipment": "جملة معدات الحاسب",
  "Wholesale Drugs and Sundries": "جملة الأدوية والمستلزمات الطبية",
  "Wholesale Food and Beverage": "جملة الأغذية والمشروبات",
  "Wholesale Footwear": "جملة الأحذية",
  "Wholesale Furniture and Home Furnishings": "جملة الأثاث والمفروشات",
  "Wholesale Hardware, Plumbing, Heating Equipment": "جملة العدد والسباكة ومعدات التدفئة",
  "Wholesale Import and Export": "جملة الاستيراد والتصدير",
  "Wholesale Luxury Goods and Jewelry": "جملة السلع الفاخرة والمجوهرات",
  "Wholesale Machinery": "جملة الآلات",
  "Wholesale Metals and Minerals": "جملة المعادن والخامات",
  "Wholesale Motor Vehicles and Parts": "جملة المركبات وقطع الغيار",
  "Wholesale Paper Products": "جملة منتجات الورق",
  "Wholesale Petroleum and Petroleum Products": "جملة النفط ومشتقاته",
  "Wholesale Photography Equipment and Supplies": "جملة معدات ومستلزمات التصوير",
  "Wholesale Raw Farm Products": "جملة المنتجات الزراعية الخام",
  "Wholesale Recyclable Materials": "جملة المواد القابلة لإعادة التدوير",
  "Wind Electric Power Generation": "توليد الكهرباء بطاقة الرياح",
  "Wireless Services": "خدمات الاتصالات اللاسلكية",
  "Women's Handbag Manufacturing": "تصنيع حقائب النساء",
  "Wood Product Manufacturing": "تصنيع منتجات الخشب",
  "Writing and Editing": "الكتابة والتحرير",
  "Zoos and Botanical Gardens": "حدائق الحيوان والنباتات",
};

// The provider's categories a member can pick by name. A name already in the lists (a field, specialty or activity) stays
// with the list, which may search more than one category.
export const providerCategories = Object.entries(INDUSTRY_AR).map(([en, ar]) => ({ en, ar })).filter(c => !fieldOf(c.ar));
const providerByArabic = new Map(providerCategories.map(c => [c.ar, c.en]));
export const providerCategory = (ar: string) => providerByArabic.get(ar);
export function findCategories(query: string) {
  const words = searchWords(query);
  return words.length ? providerCategories.filter(c => words.every(w => norm(c.ar + ' ' + c.en).includes(w))) : [];
}
