import { norm } from './places';

// Suggested services are offers a member could sell, not integrations supplied by clowzy.
// Keywords narrow provider categories that otherwise include unrelated kinds of businesses.
export const niches = [
  { label:'مكاتب العقارات', en:'Real estate agencies', field:'العقارات والبناء', aliases:['مكتب عقاري','عقارات','real estate agency'], services:'متابعة العملاء المحتملين، إعلانات، حجز معاينات', servicesEn:'Lead follow-up, advertising, viewing appointments', industries:['Real Estate Agents and Brokers'] },
  { label:'عيادات الأسنان', en:'Dental clinics', field:'الصحة والطب', aliases:['عيادة الأسنان','عيادة اسنان','عيادات اسنان','dental clinic','dentists'], services:'حجز مواعيد، متابعة عبر واتساب، إعلانات', servicesEn:'Appointment booking, WhatsApp follow-up, advertising', industries:['Dentists'] },
  { label:'عيادات التجميل', en:'Aesthetic clinics', field:'الصحة والطب', aliases:['عيادة تجميل','عيادات جلدية وتجميل','cosmetic clinic','aesthetic clinic'], services:'جلب عملاء محتملين، متابعة، حجز جلسات', servicesEn:'Lead generation, follow-up, session booking', industries:['Medical Practices','Outpatient Care Centers'], keywords:['aesthetic','cosmetic clinic','plastic surgery','تجميل','جلدية'] },
  { label:'العيادات الخاصة', en:'Private clinics', field:'الصحة والطب', aliases:['عيادة خاصة','عيادات طبية','private clinic','medical clinic'], services:'إدارة العملاء، تذكير بالمواعيد، متابعة المرضى', servicesEn:'CRM, appointment reminders, patient follow-up', industries:['Medical Practices','Outpatient Care Centers','Physicians'] },
  { label:'النوادي الرياضية', en:'Gyms and fitness clubs', field:'الصحة والطب', aliases:['نادي رياضي','جيم','gym','fitness club'], services:'جلب مشتركين، متابعة تلقائية، تجديد الاشتراكات', servicesEn:'Member acquisition, automated follow-up, membership renewals', industries:['Wellness and Fitness Services','Health, Wellness & Fitness'], keywords:['gym','fitness club','fitness center','fitness centre','نادي','نوادي','لياقة'] },
  { label:'أخصائيو التغذية', en:'Nutrition practices', field:'الصحة والطب', aliases:['أخصائي تغذية','أخصائيي التغذية','اخصائي تغذية','nutritionist','dietitian'], services:'صفحة لاستقبال العملاء، حجز استشارات، متابعة', servicesEn:'Lead funnels, consultation booking, follow-up', industries:['Wellness and Fitness Services','Medical Practices'], keywords:['nutrition','dietitian','dietician','تغذية','تغذيه'] },
  { label:'مراكز التدريب', en:'Training centers', field:'التعليم والتدريب', aliases:['مركز تدريب','training center','training centre'], services:'جلب طلاب، متابعة واتساب، إدارة التسجيل', servicesEn:'Student acquisition, WhatsApp follow-up, enrollment management', industries:['Professional Training and Coaching','Technical and Vocational Training'] },
  { label:'مراكز اللغات', en:'Language centers', field:'التعليم والتدريب', aliases:['مركز لغات','معهد لغات','language school','language center'], services:'إعلانات الدورات، تسجيل الطلاب، متابعة الاستفسارات', servicesEn:'Course advertising, student enrollment, inquiry follow-up', industries:['Language Schools'] },
  { label:'الأكاديميات الأونلاين', en:'Online academies', field:'التعليم والتدريب', aliases:['أكاديمية اونلاين','أكاديميات إلكترونية','online academy','online academies'], services:'صفحات بيع الدورات، أتمتة البريد وواتساب', servicesEn:'Course funnels, email and WhatsApp automation', industries:['E-Learning Providers','E-learning'] },
  { label:'مكاتب المحاماة', en:'Law firms', field:'المال والخدمات المهنية', aliases:['مكتب محاماة','محامي','law firm'], services:'جلب استفسارات، حجز استشارات، متابعة العملاء', servicesEn:'Inquiry generation, consultation booking, client follow-up', industries:['Law Practice','Legal Services'] },
  { label:'مكاتب المحاسبة', en:'Accounting firms', field:'المال والخدمات المهنية', aliases:['مكتب محاسبة','محاسب','accounting firm'], services:'بحث عن عملاء شركات، تواصل تجاري، متابعة', servicesEn:'B2B prospecting, business outreach, follow-up', industries:['Accounting'] },
  { label:'شركات الاستشارات', en:'Consulting firms', field:'المال والخدمات المهنية', aliases:['شركة استشارات','consulting firm','consultancy'], services:'جلب عملاء شركات، تأهيل الطلبات، حجز اجتماعات', servicesEn:'B2B lead generation, qualification, meeting booking', industries:['Business Consulting and Services','Operations Consulting'] },
  { label:'شركات المقاولات', en:'Contracting companies', field:'العقارات والبناء', aliases:['شركة مقاولات','مقاول','contractor','construction company'], services:'جلب مشاريع، التواصل مع الشركات، متابعة العروض', servicesEn:'Project leads, business outreach, quotation follow-up', industries:['Construction','Building Construction','Specialty Trade Contractors'] },
  { label:'شركات التصميم الداخلي', en:'Interior design studios', field:'العقارات والبناء', aliases:['شركة تصميم داخلي','تصميم داخلي','interior design'], services:'جلب طلبات، عرض الأعمال، حجز استشارات', servicesEn:'Lead generation, portfolio funnels, consultation booking', industries:['Interior Design'] },
  { label:'شركات الأثاث', en:'Furniture businesses', field:'العقارات والبناء', aliases:['شركة أثاث','محلات أثاث','furniture company'], services:'إعلانات، طلبات عروض أسعار، متابعة واتساب', servicesEn:'Advertising, quote requests, WhatsApp follow-up', industries:['Furniture','Retail Furniture and Home Furnishings','Furniture and Home Furnishings Manufacturing'] },
  { label:'شركات الطاقة الشمسية', en:'Solar energy companies', field:'الصناعة والطاقة والنقل', aliases:['شركة طاقة شمسية','solar company','solar energy'], services:'جلب طلبات، تأهيل العملاء، حجز معاينات', servicesEn:'Lead generation, qualification, site visits', industries:['Solar Electric Power Generation','Renewable Energy Power Generation','Building Equipment Contractors'], keywords:['solar','photovoltaic','طاقة شمسية','الطاقة الشمسية','ألواح شمسية'] },
  { label:'شركات التكييف', en:'Air conditioning companies', field:'الصناعة والطاقة والنقل', aliases:['شركة تكييف','تكييف','air conditioning','hvac'], services:'طلبات تركيب وصيانة، متابعة، تذكير بالخدمة', servicesEn:'Installation and service leads, follow-up, service reminders', industries:['Building Equipment Contractors','HVAC and Refrigeration Equipment Manufacturing'], keywords:['HVAC','air conditioning','تكييف','التكييف','تبريد'] },
  { label:'شركات التنظيف', en:'Cleaning companies', field:'الصناعة والطاقة والنقل', aliases:['شركة تنظيف','تنظيف','cleaning company'], services:'جلب طلبات، حجز زيارات، متابعة تلقائية', servicesEn:'Lead generation, visit booking, automated follow-up', industries:['Janitorial Services'] },
  { label:'شركات النقل والشحن', en:'Transport and shipping companies', field:'الصناعة والطاقة والنقل', aliases:['شركة شحن','نقل وشحن','shipping company','freight company'], services:'البحث عن عملاء شركات، التواصل، إدارة العملاء', servicesEn:'B2B prospecting, outreach, CRM', industries:['Truck Transportation','Freight and Package Transportation','Transportation, Logistics, Supply Chain and Storage'] },
  { label:'معارض السيارات', en:'Car dealerships', field:'التجارة والمتاجر', aliases:['معرض سيارات','car dealership','car dealer'], services:'جلب مهتمين، متابعة واتساب، حجز تجربة قيادة', servicesEn:'Lead generation, WhatsApp follow-up, test drive booking', industries:['Retail Motor Vehicles'] },
  { label:'تأجير السيارات', en:'Car rental agencies', field:'التجارة والمتاجر', aliases:['مكتب تأجير سيارات','car rental','rent a car'], services:'حجز سيارات، متابعة الطلبات، تجديد التأجير', servicesEn:'Vehicle booking, inquiry follow-up, rental renewals', industries:['Automotive','Retail Motor Vehicles','Consumer Goods Rental','Travel Arrangements'], keywords:['car rental','rent a car','vehicle rental','تأجير سيارات','تاجير سيارات','لتأجير السيارات'] },
  { label:'مراكز صيانة السيارات', en:'Auto repair centers', field:'التجارة والمتاجر', aliases:['مركز صيانة سيارات','ورشة سيارات','auto repair','car service'], services:'حجز صيانة، تذكير بالمواعيد، إعادة استهداف', servicesEn:'Service booking, reminders, retargeting', industries:['Vehicle Repair and Maintenance'] },
  { label:'الفنادق والشاليهات', en:'Hotels and chalets', field:'المطاعم والضيافة', aliases:['فنادق','شاليهات','hotel','chalets'], services:'صفحات حجز، متابعة الاستفسارات، تذكير الحجوزات', servicesEn:'Booking funnels, inquiry follow-up, reservation reminders', industries:['Hotels and Motels','Hospitality'] },
  { label:'مكاتب السياحة والسفر', en:'Travel agencies', field:'المطاعم والضيافة', aliases:['مكتب سياحة','وكالة سفر','travel agency'], services:'جلب طلبات سفر، متابعة واتساب، عروض رحلات', servicesEn:'Travel leads, WhatsApp follow-up, trip offers', industries:['Travel Arrangements'] },
  { label:'المطاعم', en:'Restaurants', field:'المطاعم والضيافة', aliases:['مطعم','restaurants','restaurant'], services:'إعلانات، إدارة العملاء، إعادة العملاء للطلب', servicesEn:'Advertising, CRM, repeat-customer campaigns', industries:['Restaurants'] },
  { label:'شركات البرمجيات', en:'Software companies', field:'التقنية والاتصالات', aliases:['شركة برمجيات','software company','software development'], services:'جلب عملاء شركات، تواصل بالبريد، حجز اجتماعات', servicesEn:'B2B lead generation, email outreach, meeting booking', industries:['Software Development','IT System Custom Software Development'] },
  { label:'وكالات التسويق', en:'Marketing agencies', field:'التسويق والإعلام', aliases:['وكالة تسويق','marketing agency','digital agency'], services:'جلب عملاء، حجز اجتماعات، متابعة العروض', servicesEn:'Lead generation, meeting booking, proposal follow-up', industries:['Marketing Services','Advertising Services'] },
  { label:'وكالات التصميم', en:'Design agencies', field:'التسويق والإعلام', aliases:['وكالة تصميم','design agency','design studio'], services:'تواصل تجاري، جلب مشاريع، أتمتة متابعة المبيعات', servicesEn:'Business outreach, project leads, sales follow-up', industries:['Graphic Design','Design Services'] },
  { label:'شركات الإنتاج', en:'Production companies', field:'التسويق والإعلام', aliases:['شركة إنتاج','إنتاج فيديو','video production','production company'], services:'البحث عن شركات تحتاج تصويرًا ومحتوى', servicesEn:'Prospecting for businesses needing video and content', industries:['Media Production','Movies, Videos, and Sound'] },
  { label:'شركات التوظيف', en:'Recruitment agencies', field:'المال والخدمات المهنية', aliases:['شركة توظيف','recruitment agency','staffing agency'], services:'البحث عن شركات، تواصل تجاري، متابعة احتياجات التوظيف', servicesEn:'Company prospecting, business outreach, hiring follow-up', industries:['Staffing and Recruiting','Executive Search Services'] },
  { label:'متاجر التجارة الإلكترونية', en:'E-commerce stores', field:'التجارة والمتاجر', aliases:['متجر إلكتروني','متاجر الكترونية','ecommerce','e-commerce'], services:'إعلانات، أتمتة البريد والرسائل، استعادة السلات', servicesEn:'Advertising, email and SMS automation, cart recovery', industries:['Online and Mail Order Retail','Internet Marketplace Platforms'] },
  { label:'شركات الجملة والتوزيع', en:'Wholesale and distribution businesses', field:'التجارة والمتاجر', aliases:['شركة توزيع','تجارة الجملة','wholesale','distributor'], services:'البحث عن مشترين شركات، التواصل، متابعة الطلبات', servicesEn:'B2B buyer prospecting, outreach, order follow-up', industries:['Wholesale','Wholesale Import and Export'] },
  { label:'المصانع', en:'Manufacturers', field:'الصناعة والطاقة والنقل', aliases:['مصنع','مصانع','factory','manufacturers'], services:'البحث عن موزعين ومشترين من الشركات', servicesEn:'Distributor and B2B buyer prospecting', industries:['Manufacturing','Industrial Machinery Manufacturing'] },
  { label:'محلات المجوهرات', en:'Jewelry stores', field:'التجارة والمتاجر', aliases:['محل مجوهرات','محلات ذهب','jewelry store','jewellery'], services:'إعلانات، استفسارات واتساب، متابعة المهتمين', servicesEn:'Advertising, WhatsApp leads, inquiry follow-up', industries:['Retail Luxury Goods and Jewelry','Luxury Goods & Jewelry'], keywords:['jewel','jewelry','jewellery','مجوهرات','ذهب'] },
  { label:'منظمو الأعراس', en:'Wedding planners', field:'المطاعم والضيافة', aliases:['منظم أعراس','منظمي الاعراس','wedding planner'], services:'جلب طلبات، حجز استشارات، متابعة الحجوزات', servicesEn:'Lead generation, consultation booking, booking follow-up', industries:['Events Services'], keywords:['wedding','bridal','زفاف','اعراس','أعراس'] },
  { label:'استوديوهات التصوير', en:'Photography studios', field:'التسويق والإعلام', aliases:['استوديو تصوير','مصوريين','photography studio','photographer'], services:'جلب طلبات، حجز جلسات، متابعة العملاء', servicesEn:'Lead generation, session booking, client follow-up', industries:['Photography'] },
  { label:'شركات الأمن والكاميرات', en:'Security and CCTV companies', field:'الصناعة والطاقة والنقل', aliases:['شركة كاميرات','كاميرات مراقبة','cctv','security systems'], services:'جلب عملاء شركات، طلبات معاينة، تواصل تجاري', servicesEn:'B2B lead generation, site visits, business outreach', industries:['Security Systems Services','Security and Investigations'], keywords:['security system','CCTV','surveillance','كاميرات','انظمة امن','أنظمة أمن'] },
  { label:'شركات المسابح', en:'Swimming pool companies', field:'العقارات والبناء', aliases:['شركة مسابح','مسابح','swimming pool company','pool contractor'], services:'طلبات من أصحاب الفلل والمشاريع، حجز معاينات', servicesEn:'Villa and project leads, site visit booking', industries:['Specialty Trade Contractors','Construction'], keywords:['swimming pool','pool construction','pool maintenance','مسابح','مسبح'] },
  { label:'شركات الألمنيوم والزجاج', en:'Aluminum and glass companies', field:'العقارات والبناء', aliases:['ألمنيوم وزجاج','المنيوم','aluminum and glass','aluminium'], services:'جلب مشاريع، تواصل مع المقاولين، طلبات تسعير', servicesEn:'Project leads, contractor outreach, quotation requests', industries:['Glass Product Manufacturing','Architectural and Structural Metal Manufacturing','Building Finishing Contractors'], keywords:['aluminum','aluminium','glass','ألمنيوم','المنيوم','زجاج'] },
  { label:'مورّدو المطاعم', en:'Restaurant suppliers', field:'التجارة والمتاجر', aliases:['موردو المطاعم','مورد مطاعم','restaurant supplier','foodservice supplier'], services:'البحث عن مطاعم وشركات ضيافة، تواصل تجاري', servicesEn:'Restaurant and hospitality prospecting, B2B outreach', industries:['Wholesale Food and Beverage','Wholesale Machinery'], keywords:['restaurant','foodservice','food service','catering equipment','مطاعم','مستلزمات مطاعم','تجهيزات مطاعم'] },
  { label:'مورّدو المعدات الطبية', en:'Medical equipment suppliers', field:'الصحة والطب', aliases:['موردو المعدات الطبية','مورد معدات طبية','medical equipment supplier','medical distributor'], services:'البحث عن عيادات ومستشفيات، تواصل تجاري', servicesEn:'Clinic and hospital prospecting, B2B outreach', industries:['Wholesale Machinery','Medical Device','Medical Equipment Manufacturing'], keywords:['medical','healthcare','dental equipment','معدات طبية','اجهزة طبية','أجهزة طبية'] },
  { label:'شركات الأمن السيبراني', en:'Cybersecurity companies', field:'التقنية والاتصالات', aliases:['أمن سيبراني','الامن السيبراني','cybersecurity','cyber security'], services:'البحث عن عملاء شركات، حجز اجتماعات، متابعة العروض', servicesEn:'B2B prospecting, meeting booking, proposal follow-up', industries:['Computer and Network Security','Data Security Software Products'] },
  // Beauty and personal care (client request 2026-10-05). Most salons carry no provider category: anyIndustry searches the
  // words in every category (minus ANY_INDUSTRY_EXCLUDED), then this niche's categories without them (free counts, Lebanon: 6 -> 231 salons).
  { label:'صالونات التجميل النسائية', en:'Beauty salons', field:'التجارة والمتاجر', aliases:['صالون تجميل','صالونات تجميل','صالون نسائي','مشغل نسائي','مشاغل نسائية','beauty salon','hair salon','ladies salon'], services:'حجز مواعيد، تذكير واتساب، إعلانات محلية', servicesEn:'Appointment booking, WhatsApp reminders, local ads', industries:['Personal Care Services'], anyIndustry:true, keywords:['beauty salon','ladies salon','hair salon','beauty center','beauty centre','beauty lounge','beauty studio','hair studio','hairdresser','coiffure','صالون','مركز تجميل','مشغل نسائي'] },
  { label:'صالونات الحلاقة الرجالية', en:'Barbershops', field:'التجارة والمتاجر', aliases:['حلاق','حلاقين','صالون رجالي','صالون حلاقة','barber','barbershop','gents salon'], services:'حجز مواعيد، برامج ولاء، إعلانات محلية', servicesEn:'Appointment booking, loyalty programs, local ads', industries:['Personal Care Services'], anyIndustry:true, keywords:['barber','barbershop','barber shop','gents salon','men salon','حلاق','حلاقة'] },
  { label:'مراكز العناية بالأظافر', en:'Nail salons', field:'التجارة والمتاجر', aliases:['أظافر','اظافر','مانيكير','nail salon','nails'], services:'حجز مواعيد، عروض موسمية، متابعة العملاء', servicesEn:'Appointment booking, seasonal offers, client follow-up', industries:['Personal Care Services'], anyIndustry:true, keywords:['nail salon','nail spa','nail studio','nails','manicure','أظافر'] },
  { label:'خبيرات المكياج', en:'Makeup artists', field:'التجارة والمتاجر', aliases:['مكياج','ميك اب','خبيرة مكياج','makeup artist','make up artist'], services:'حجز مناسبات، عرض الأعمال، متابعة العرائس', servicesEn:'Event booking, portfolio funnels, bridal follow-up', industries:['Personal Care Services'], anyIndustry:true, keywords:['makeup artist','make up artist','makeup studio','bridal makeup','مكياج','ميك اب'] },
  { label:'مراكز السبا والمساج', en:'Spas and massage centers', field:'التجارة والمتاجر', aliases:['سبا','مساج','spa','massage center'], services:'حجز جلسات، باقات وعروض، تذكير بالمواعيد', servicesEn:'Session booking, packages and offers, reminders', industries:['Personal Care Services','Wellness and Fitness Services','Health, Wellness & Fitness','Alternative Medicine'], keywords:['spa','massage','سبا','مساج'] },
  { label:'مراكز الليزر وإزالة الشعر', en:'Laser hair removal centers', field:'الصحة والطب', aliases:['ليزر','إزالة الشعر','مركز ليزر','laser clinic','laser hair removal'], services:'جلب عملاء، حجز جلسات، متابعة الباقات', servicesEn:'Lead generation, session booking, package follow-up', industries:['Personal Care Services','Medical Practices','Wellness and Fitness Services','Health, Wellness & Fitness','Outpatient Care Centers'], keywords:['laser','hair removal','ليزر'] },
  { label:'متاجر مستحضرات التجميل', en:'Cosmetics stores', field:'التجارة والمتاجر', aliases:['مستحضرات تجميل','محل مكياج','cosmetics store','beauty store'], services:'إعلانات، متجر إلكتروني، استعادة السلات', servicesEn:'Advertising, online store, cart recovery', industries:['Retail Health and Personal Care Products','Cosmetics'] },
  { label:'محلات العطور', en:'Perfume stores', field:'التجارة والمتاجر', aliases:['عطور','عطر','دهن عود','perfume store','perfumes'], services:'إعلانات، متجر إلكتروني، حملات المناسبات', servicesEn:'Advertising, online store, seasonal campaigns', industries:['Retail','Cosmetics','Retail Health and Personal Care Products','Personal Care Product Manufacturing','Retail Luxury Goods and Jewelry','Consumer Goods'], keywords:['perfume','perfumes','fragrance','fragrances','oud','عطور','عطر'] },
  { label:'علامات ومصانع مستحضرات التجميل', en:'Cosmetics brands and manufacturers', field:'التجارة والمتاجر', aliases:['مصنع مستحضرات تجميل','براند تجميل','cosmetics brand','skincare brand'], services:'البحث عن موزعين ومتاجر، تسويق المنتجات', servicesEn:'Distributor and retailer prospecting, product marketing', industries:['Personal Care Product Manufacturing','Cosmetics'] },
  // Health
  { label:'مراكز العلاج الطبيعي', en:'Physiotherapy centers', field:'الصحة والطب', aliases:['علاج طبيعي','مركز علاج طبيعي','physiotherapy','physical therapy'], services:'حجز جلسات، متابعة المرضى، إعلانات', servicesEn:'Session booking, patient follow-up, advertising', industries:['Physical, Occupational and Speech Therapists','Medical Practices','Wellness and Fitness Services','Hospitals and Health Care'], keywords:['physiotherapy','physical therapy','rehabilitation','علاج طبيعي','تأهيل'] },
  { label:'محلات النظارات والبصريات', en:'Optical stores', field:'الصحة والطب', aliases:['نظارات','بصريات','محل نظارات','optical store','optics','eyewear'], services:'إعلانات، تذكير بفحص النظر، عروض', servicesEn:'Advertising, eye-test reminders, offers', industries:['Optometrists','Retail','Retail Health and Personal Care Products','Medical Practices'], keywords:['optical','optics','optician','eyewear','glasses','نظارات','بصريات'] },
  { label:'العيادات البيطرية', en:'Veterinary clinics', field:'الصحة والطب', aliases:['عيادة بيطرية','بيطري','vet clinic','veterinary clinic'], services:'حجز مواعيد، تذكير بالتطعيمات، متابعة', servicesEn:'Appointment booking, vaccination reminders, follow-up', industries:['Veterinary Services','Veterinary'] },
  { label:'الرعاية الصحية المنزلية', en:'Home healthcare providers', field:'الصحة والطب', aliases:['رعاية منزلية','تمريض منزلي','home healthcare','home care'], services:'جلب طلبات، حجز زيارات، متابعة الأسر', servicesEn:'Lead generation, visit booking, family follow-up', industries:['Home Health Care Services'] },
  { label:'الصيدليات', en:'Pharmacies', field:'الصحة والطب', aliases:['صيدلية','صيدليات','pharmacy','pharmacies'], services:'إعلانات، توصيل الطلبات، برامج ولاء', servicesEn:'Advertising, order delivery, loyalty programs', industries:['Retail Pharmacies'] },
  { label:'مراكز الطب البديل والحجامة', en:'Alternative medicine and cupping centers', field:'الصحة والطب', aliases:['حجامة','طب بديل','alternative medicine','cupping'], services:'حجز جلسات، إعلانات محلية، متابعة', servicesEn:'Session booking, local ads, follow-up', industries:['Alternative Medicine'] },
  { label:'استوديوهات اليوغا والبيلاتس', en:'Yoga and pilates studios', field:'الصحة والطب', aliases:['يوغا','بيلاتس','yoga studio','pilates studio'], services:'جلب مشتركين، حجز حصص، تجديد الاشتراكات', servicesEn:'Member acquisition, class booking, renewals', industries:['Wellness and Fitness Services','Health, Wellness & Fitness'], keywords:['yoga','pilates','يوغا','بيلاتس'] },
  // Food and hospitality
  { label:'المقاهي', en:'Cafés and coffee shops', field:'المطاعم والضيافة', aliases:['مقهى','كافيه','كوفي','محمصة','cafe','coffee shop'], services:'إعلانات، برامج ولاء، إدارة العملاء', servicesEn:'Advertising, loyalty programs, CRM', industries:['Restaurants','Food and Beverage Services','Food and Beverage Retail'], keywords:['cafe','café','coffee','roastery','كافيه','مقهى','قهوة'] },
  { label:'المخابز ومحلات الحلويات', en:'Bakeries and sweet shops', field:'المطاعم والضيافة', aliases:['مخبز','مخابز','حلويات','محل حلويات','bakery','sweets shop','patisserie'], services:'إعلانات، طلبات المناسبات، توصيل', servicesEn:'Advertising, event orders, delivery', industries:['Restaurants','Food and Beverage Services','Food and Beverage Manufacturing','Food and Beverage Retail','Retail Groceries','Food & Beverages'], keywords:['bakery','bakeries','sweets','pastry','patisserie','chocolate','مخبز','مخابز','حلويات'] },
  { label:'شركات الضيافة والتموين', en:'Catering companies', field:'المطاعم والضيافة', aliases:['تموين','ضيافة','بوفيه','catering'], services:'جلب طلبات شركات ومناسبات، عروض أسعار', servicesEn:'Corporate and event leads, quotations', industries:['Caterers'] },
  { label:'عربات الطعام', en:'Food trucks', field:'المطاعم والضيافة', aliases:['فود ترك','عربة طعام','food truck'], services:'إعلانات محلية، حجز مناسبات، برامج ولاء', servicesEn:'Local ads, event booking, loyalty programs', industries:['Mobile Food Services'] },
  { label:'شركات تنظيم الفعاليات', en:'Event management companies', field:'المطاعم والضيافة', aliases:['تنظيم فعاليات','تنظيم مؤتمرات','event management','events company'], services:'جلب عملاء شركات، عروض، متابعة', servicesEn:'Corporate leads, proposals, follow-up', industries:['Events Services'] },
  // Retail and trade
  { label:'السوبرماركت والبقالات', en:'Supermarkets and groceries', field:'التجارة والمتاجر', aliases:['سوبرماركت','بقالة','تموينات','supermarket','grocery'], services:'إعلانات، توصيل الطلبات، عروض أسبوعية', servicesEn:'Advertising, delivery, weekly offers', industries:['Retail Groceries'] },
  { label:'محلات الملابس والأزياء', en:'Clothing stores', field:'التجارة والمتاجر', aliases:['محل ملابس','بوتيك','عبايات','clothing store','boutique'], services:'إعلانات، متجر إلكتروني، حملات المواسم', servicesEn:'Advertising, online store, seasonal campaigns', industries:['Retail Apparel and Fashion'] },
  { label:'محلات الجوالات والإلكترونيات', en:'Mobile and electronics stores', field:'التجارة والمتاجر', aliases:['محل جوالات','جوالات','الكترونيات','mobile shop','electronics store'], services:'إعلانات، متجر إلكتروني، عروض', servicesEn:'Advertising, online store, offers', industries:['Retail Appliances, Electrical, and Electronic Equipment','Consumer Electronics'] },
  { label:'محلات الورد والهدايا', en:'Florists and gift shops', field:'التجارة والمتاجر', aliases:['ورد','محل ورد','هدايا','florist','gift shop'], services:'إعلانات المناسبات، توصيل، متجر إلكتروني', servicesEn:'Occasion ads, delivery, online store', industries:['Retail Florists','Retail Office Supplies and Gifts'] },
  { label:'محلات قطع غيار السيارات', en:'Auto parts stores', field:'التجارة والمتاجر', aliases:['قطع غيار','قطع غيار سيارات','spare parts','auto parts'], services:'البحث عن ورش ومعارض، تواصل تجاري', servicesEn:'Workshop and dealer prospecting, B2B outreach', industries:['Wholesale Motor Vehicles and Parts','Motor Vehicle Parts Manufacturing','Retail Motor Vehicles','Automotive'], keywords:['spare parts','auto parts','car parts','قطع غيار'] },
  { label:'مغاسل وتلميع السيارات', en:'Car wash and detailing', field:'التجارة والمتاجر', aliases:['مغسلة سيارات','تلميع','غسيل سيارات','car wash','car detailing'], services:'حجز مواعيد، اشتراكات شهرية، عروض', servicesEn:'Appointment booking, monthly plans, offers', industries:['Vehicle Repair and Maintenance','Automotive','Consumer Services','Personal and Laundry Services'], keywords:['car wash','car detailing','detailing','ceramic coating','غسيل سيارات','تلميع'] },
  { label:'المغاسل والدراي كلين', en:'Laundries and dry cleaners', field:'التجارة والمتاجر', aliases:['مغسلة','مغسلة ملابس','دراي كلين','laundry','dry cleaning'], services:'طلبات استلام وتوصيل، اشتراكات، تذكير', servicesEn:'Pickup and delivery orders, subscriptions, reminders', industries:['Laundry and Drycleaning Services','Personal and Laundry Services'] },
  { label:'محلات مواد البناء', en:'Building materials stores', field:'العقارات والبناء', aliases:['مواد بناء','مواد البناء','building materials'], services:'البحث عن مقاولين، تواصل تجاري، عروض أسعار', servicesEn:'Contractor prospecting, B2B outreach, quotations', industries:['Retail Building Materials and Garden Equipment','Wholesale Building Materials'] },
  // Real estate and construction
  { label:'شركات التطوير العقاري', en:'Real estate developers', field:'العقارات والبناء', aliases:['تطوير عقاري','مطور عقاري','real estate developer'], services:'جلب مشترين ومستثمرين، إعلانات المشاريع', servicesEn:'Buyer and investor leads, project advertising', industries:['Real Estate','Commercial Real Estate','Leasing Residential Real Estate'], keywords:['real estate development','developer','developers','developments','تطوير عقاري'] },
  { label:'شركات إدارة الأملاك', en:'Property management companies', field:'العقارات والبناء', aliases:['إدارة أملاك','ادارة املاك','property management'], services:'جلب ملاك، متابعة المستأجرين، أتمتة التحصيل', servicesEn:'Owner leads, tenant follow-up, collection automation', industries:['Real Estate','Leasing Residential Real Estate','Leasing Non-residential Real Estate','Facilities Services'], keywords:['property management','إدارة أملاك','إدارة الأملاك','ادارة الاملاك'] },
  { label:'شركات إدارة المرافق والصيانة', en:'Facility management and maintenance', field:'العقارات والبناء', aliases:['صيانة عامة','إدارة مرافق','facility management','maintenance company'], services:'البحث عن عملاء شركات، عقود صيانة', servicesEn:'B2B prospecting, maintenance contracts', industries:['Facilities Services','Repair and Maintenance'] },
  { label:'شركات تنسيق الحدائق', en:'Landscaping companies', field:'العقارات والبناء', aliases:['تنسيق حدائق','لاندسكيب','landscaping'], services:'طلبات أصحاب الفلل والمشاريع، حجز معاينات', servicesEn:'Villa and project leads, site visits', industries:['Landscaping Services'] },
  { label:'شركات المطابخ', en:'Kitchen companies', field:'العقارات والبناء', aliases:['مطابخ','مطبخ','kitchens','kitchen company'], services:'جلب طلبات، حجز معاينات، عروض أسعار', servicesEn:'Lead generation, site visits, quotations', industries:['Furniture','Furniture and Home Furnishings Manufacturing','Retail Furniture and Home Furnishings','Interior Design','Household and Institutional Furniture Manufacturing'], keywords:['kitchen','kitchens','مطابخ','مطبخ'] },
  { label:'شركات مكافحة الحشرات', en:'Pest control companies', field:'الصناعة والطاقة والنقل', aliases:['مكافحة حشرات','مكافحة الحشرات','pest control'], services:'طلبات منازل وشركات، عقود دورية، تذكير', servicesEn:'Home and business leads, recurring contracts, reminders', industries:['Environmental Services','Janitorial Services','Facilities Services','Consumer Services'], keywords:['pest control','مكافحة الحشرات','مكافحة حشرات'] },
  { label:'شركات نقل العفش', en:'Moving companies', field:'الصناعة والطاقة والنقل', aliases:['نقل عفش','نقل أثاث','movers','moving company'], services:'جلب طلبات، عروض أسعار، متابعة واتساب', servicesEn:'Lead generation, quotations, WhatsApp follow-up', industries:['Truck Transportation','Freight and Package Transportation','Transportation, Logistics, Supply Chain and Storage','Consumer Services'], keywords:['movers','moving','relocation','نقل عفش','نقل أثاث','نقل اثاث'] },
  // Education
  { label:'المدارس الخاصة', en:'Private schools', field:'التعليم والتدريب', aliases:['مدرسة خاصة','مدارس اهلية','مدارس أهلية','private school','international school'], services:'جلب طلبات تسجيل، حملات القبول، متابعة الأهالي', servicesEn:'Enrollment leads, admission campaigns, parent follow-up', industries:['Primary and Secondary Education'] },
  { label:'الحضانات ورياض الأطفال', en:'Nurseries and kindergartens', field:'التعليم والتدريب', aliases:['حضانة','روضة','رياض أطفال','nursery','kindergarten'], services:'حملات التسجيل، متابعة الأهالي، جولات تعريفية', servicesEn:'Enrollment campaigns, parent follow-up, open days', industries:['Child Day Care Services','Primary and Secondary Education'], keywords:['nursery','kindergarten','preschool','daycare','حضانة','روضة'] },
  { label:'مراكز الدروس الخصوصية', en:'Tutoring centers', field:'التعليم والتدريب', aliases:['دروس خصوصية','تقوية','tutoring','tuition center'], services:'جلب طلاب، تسجيل، متابعة الأهالي', servicesEn:'Student acquisition, enrollment, parent follow-up', industries:['Education','Primary and Secondary Education','Professional Training and Coaching'], keywords:['tutoring','tuition','tutor','دروس خصوصية','تقوية'] },
  // Professional services
  { label:'وسطاء التأمين', en:'Insurance brokers', field:'المال والخدمات المهنية', aliases:['وسيط تأمين','وكالة تأمين','insurance broker'], services:'جلب عملاء أفراد وشركات، متابعة التجديد', servicesEn:'Individual and B2B leads, renewal follow-up', industries:['Insurance Agencies and Brokerages'] },
  { label:'مكاتب الاستقدام', en:'Manpower and recruitment offices', field:'المال والخدمات المهنية', aliases:['استقدام','مكتب استقدام','manpower','recruitment office'], services:'جلب طلبات أسر وشركات، متابعة واتساب', servicesEn:'Family and business leads, WhatsApp follow-up', industries:['Staffing and Recruiting','Human Resources Services'], keywords:['manpower','recruitment office','domestic workers','استقدام'] },
  { label:'مكاتب الترجمة', en:'Translation offices', field:'المال والخدمات المهنية', aliases:['ترجمة','ترجمة معتمدة','translation office'], services:'جلب عملاء شركات، عروض أسعار، متابعة', servicesEn:'B2B leads, quotations, follow-up', industries:['Translation and Localization'] },
  // Marketing and technology
  { label:'شركات الطباعة', en:'Printing companies', field:'التسويق والإعلام', aliases:['مطبعة','طباعة','printing press','printing company'], services:'البحث عن شركات تحتاج مطبوعات، عروض أسعار', servicesEn:'Prospecting for print buyers, quotations', industries:['Printing Services'] },
  { label:'مطوّرو تطبيقات الجوال', en:'Mobile app developers', field:'التقنية والاتصالات', aliases:['تطوير تطبيقات','برمجة تطبيقات','mobile app development','app developers'], services:'جلب عملاء شركات، حجز اجتماعات، عروض', servicesEn:'B2B leads, meeting booking, proposals', industries:['Software Development','IT Services and IT Consulting','Mobile Computing Software Products'], keywords:['mobile app','mobile apps','app development','تطبيقات'] },
  { label:'شركات تصميم المواقع', en:'Web design companies', field:'التقنية والاتصالات', aliases:['تصميم مواقع','برمجة مواقع','web design','web development'], services:'جلب عملاء، حجز اجتماعات، متابعة العروض', servicesEn:'Lead generation, meeting booking, proposal follow-up', industries:['Software Development','IT Services and IT Consulting','Design Services','Marketing Services'], keywords:['web design','website design','web development','تصميم مواقع'] },
  // Industry
  { label:'مصانع الأغذية', en:'Food manufacturers', field:'الصناعة والطاقة والنقل', aliases:['مصنع أغذية','مصانع غذائية','food factory','food manufacturer'], services:'البحث عن موزعين ومتاجر، تواصل تجاري', servicesEn:'Distributor and retailer prospecting, B2B outreach', industries:['Food and Beverage Manufacturing','Food Production'] },
  { label:'المزارع', en:'Farms', field:'الصناعة والطاقة والنقل', aliases:['مزرعة','مزارع','farm','farms'], services:'البحث عن مشترين وموزعين، تواصل تجاري', servicesEn:'Buyer and distributor prospecting, B2B outreach', industries:['Farming','Agriculture'] },
] as const;

export type Niche = (typeof niches)[number];
export type NicheName = Niche['label'];
export const nicheOf = (label:string) => niches.find(n => n.label === label);
export const knownNiche = (text:string) => niches.find(n => [n.label,n.en,...n.aliases].some(s => norm(s) === norm(text)));
export const nicheKeywords = (label?:string): readonly string[] => {
  const n=nicheOf(label||''); return n && 'keywords' in n ? n.keywords : [];
};
// anyIndustry niches: two stages with the keywords in every category but these, then two with the niche's categories and
// without the keywords. Excluded: the provider's alcohol, nightlife and gambling categories (never searched; also left out of
// src/lib/industries.ts), and categories whose staff match the words without being the business (counted 2026-10-05: AE
// barbers 764, of which 30 hotel, hospital or restaurant staff).
export const ANY_INDUSTRY_EXCLUDED = ['Bars, Taverns, and Nightclubs','Breweries','Distilleries','Gambling Facilities and Casinos','Wholesale Alcoholic Beverages','Wine & Spirits','Wineries',
  'Hospitality','Hotels and Motels','Hospitals and Health Care','Hospitals','Restaurants','Food and Beverage Services','Airlines and Aviation','Armed Forces'];
export const anyIndustry = (label?:string) => { const n=nicheOf(label||''); return !!n && 'anyIndustry' in n; };
// Search words: normalized, punctuation dropped (shared with the provider categories' search).
export const searchWords = (query:string) => norm(query).replace(/[^\p{L}\p{N}]+/gu,' ').trim().split(/\s+/).filter(Boolean);
export function findNiches(query:string, field='') {
  const words=searchWords(query);
  return niches.filter(n => (!field || n.field===field) && words.every(w => norm([n.label,n.en,...n.aliases].join(' ')).includes(w)));
}
