import { norm } from './places';

// Suggested services are offers a member could sell, not integrations supplied by clowzy.
// Keywords narrow provider categories that otherwise include unrelated kinds of businesses.
export const niches = [
  { label:'مكاتب العقارات', en:'Real estate agencies', field:'العقارات والبناء', aliases:['مكتب عقاري','عقارات','real estate agency'], services:'متابعة العملاء المحتملين، إعلانات، حجز معاينات', servicesEn:'Lead follow-up, advertising, viewing appointments', industries:['Real Estate Agents and Brokers'] },
  { label:'عيادات الأسنان', en:'Dental clinics', field:'الصحة والطب', aliases:['عيادة الأسنان','عيادة اسنان','عيادات اسنان','dental clinic','dentists'], services:'حجز مواعيد، متابعة عبر واتساب، إعلانات', servicesEn:'Appointment booking, WhatsApp follow-up, advertising', industries:['Dentists'] },
  { label:'عيادات التجميل', en:'Aesthetic clinics', field:'الصحة والطب', aliases:['عيادة تجميل','عيادات جلدية وتجميل','cosmetic clinic','aesthetic clinic'], services:'جلب عملاء محتملين، متابعة، حجز جلسات', servicesEn:'Lead generation, follow-up, session booking', industries:['Medical Practices','Outpatient Care Centers'], keywords:['aesthetic','cosmetic clinic','plastic surgery','تجميل','جلدية'] },
  { label:'العيادات الخاصة', en:'Private clinics', field:'الصحة والطب', aliases:['عيادة خاصة','عيادات طبية','private clinic','medical clinic'], services:'إدارة العملاء، تذكير بالمواعيد، متابعة المرضى', servicesEn:'CRM, appointment reminders, patient follow-up', industries:['Medical Practices','Outpatient Care Centers','Physicians'] },
  { label:'النوادي الرياضية', en:'Gyms and fitness clubs', field:'الصحة والطب', aliases:['نادي رياضي','جيم','gym','fitness club'], services:'جلب مشتركين، متابعة تلقائية، تجديد الاشتراكات', servicesEn:'Member acquisition, automated follow-up, membership renewals', industries:['Wellness and Fitness Services','Health, Wellness & Fitness'], keywords:['gym','fitness club','fitness center','fitness centre','نادي','نوادي','لياقة'] },
  { label:'أخصائيو التغذية', en:'Nutrition practices', field:'الصحة والطب', aliases:['أخصائي تغذية','أخصائيي التغذية','اخصائي تغذية','nutritionist','dietitian'], services:'صفحة لاستقبال العملاء، حجز استشارات، متابعة', servicesEn:'Lead funnels, consultation booking, follow-up', industries:['Wellness and Fitness Services','Medical Practices'], keywords:['nutrition','dietitian','dietician','تغذية','تغذيه'] },
  { label:'مراكز التدريب', en:'Training centers', field:'التعليم والتدريب', aliases:['مركز تدريب','training center','training centre'], services:'جلب طلاب، متابعة واتساب، إدارة التسجيل', servicesEn:'Student acquisition, WhatsApp follow-up, enrollment management', industries:['Professional Training and Coaching','Technical and Vocational Training'] },
  { label:'مراكز اللغات', en:'Language centers', field:'التعليم والتدريب', aliases:['مركز لغات','معهد لغات','language school','language center'], services:'إعلانات الدورات، تسجيل الطلاب، متابعة الاستفسارات', servicesEn:'Course advertising, student enrollment, inquiry follow-up', industries:['Language Schools'] },
  { label:'الأكاديميات الأونلاين', en:'Online academies', field:'التعليم والتدريب', aliases:['أكاديمية اونلاين','أكاديميات إلكترونية','online academy','online academies'], services:'صفحات بيع الدورات، أتمتة البريد وواتساب', servicesEn:'Course funnels, email and WhatsApp automation', industries:['E-Learning Providers','E-learning'] },
  { label:'مكاتب المحاماة', en:'Law firms', field:'المال والخدمات المهنية', aliases:['مكتب محاماة','محامي','law firm'], services:'جلب استفسارات، حجز استشارات، متابعة العملاء', servicesEn:'Inquiry generation, consultation booking, client follow-up', industries:['Law Practice','Legal Services'] },
  { label:'مكاتب المحاسبة', en:'Accounting firms', field:'المال والخدمات المهنية', aliases:['مكتب محاسبة','محاسب','accounting firm'], services:'بحث عن عملاء شركات، تواصل تجاري، متابعة', servicesEn:'B2B prospecting, business outreach, follow-up', industries:['Accounting'] },
  { label:'شركات الاستشارات', en:'Consulting firms', field:'المال والخدمات المهنية', aliases:['شركة استشارات','consulting firm','consultancy'], services:'جلب عملاء شركات، تأهيل الطلبات، حجز اجتماعات', servicesEn:'B2B lead generation, qualification, meeting booking', industries:['Business Consulting and Services','Operations Consulting'] },
  { label:'شركات المقاولات', en:'Contracting companies', field:'العقارات والبناء', aliases:['شركة مقاولات','مقاول','contractor','construction company'], services:'جلب مشاريع، التواصل مع الشركات، متابعة العروض', servicesEn:'Project leads, business outreach, quotation follow-up', industries:['Construction','Building Construction','Specialty Trade Contractors'] },
  { label:'شركات التصميم الداخلي', en:'Interior design studios', field:'العقارات والبناء', aliases:['شركة تصميم داخلي','تصميم داخلي','interior design'], services:'جلب طلبات، عرض الأعمال، حجز استشارات', servicesEn:'Lead generation, portfolio funnels, consultation booking', industries:['Interior Design'] },
  { label:'شركات الأثاث', en:'Furniture businesses', field:'العقارات والبناء', aliases:['شركة أثاث','محلات أثاث','furniture company'], services:'إعلانات، طلبات عروض أسعار، متابعة واتساب', servicesEn:'Advertising, quote requests, WhatsApp follow-up', industries:['Furniture','Retail Furniture and Home Furnishings','Furniture and Home Furnishings Manufacturing'] },
  { label:'شركات الطاقة الشمسية', en:'Solar energy companies', field:'الصناعة والطاقة والنقل', aliases:['شركة طاقة شمسية','solar company','solar energy'], services:'جلب طلبات، تأهيل العملاء، حجز معاينات', servicesEn:'Lead generation, qualification, site visits', industries:['Solar Electric Power Generation','Renewable Energy Power Generation','Building Equipment Contractors'], keywords:['solar','photovoltaic','طاقة شمسية','الطاقة الشمسية','ألواح شمسية'] },
  { label:'شركات التكييف', en:'Air conditioning companies', field:'الصناعة والطاقة والنقل', aliases:['شركة تكييف','تكييف','air conditioning','hvac'], services:'طلبات تركيب وصيانة، متابعة، تذكير بالخدمة', servicesEn:'Installation and service leads, follow-up, service reminders', industries:['Building Equipment Contractors','HVAC and Refrigeration Equipment Manufacturing'], keywords:['HVAC','air conditioning','تكييف','التكييف','تبريد'] },
  { label:'شركات التنظيف', en:'Cleaning companies', field:'الصناعة والطاقة والنقل', aliases:['شركة تنظيف','تنظيف','cleaning company'], services:'جلب طلبات، حجز زيارات، متابعة تلقائية', servicesEn:'Lead generation, visit booking, automated follow-up', industries:['Janitorial Services'] },
  { label:'شركات النقل والشحن', en:'Transport and shipping companies', field:'الصناعة والطاقة والنقل', aliases:['شركة شحن','نقل وشحن','shipping company','freight company'], services:'البحث عن عملاء شركات، التواصل، إدارة العملاء', servicesEn:'B2B prospecting, outreach, CRM', industries:['Truck Transportation','Freight and Package Transportation','Transportation, Logistics, Supply Chain and Storage'] },
  { label:'معارض السيارات', en:'Car dealerships', field:'التجارة والمتاجر', aliases:['معرض سيارات','car dealership','car dealer'], services:'جلب مهتمين، متابعة واتساب، حجز تجربة قيادة', servicesEn:'Lead generation, WhatsApp follow-up, test drive booking', industries:['Retail Motor Vehicles'] },
  { label:'تأجير السيارات', en:'Car rental agencies', field:'التجارة والمتاجر', aliases:['مكتب تأجير سيارات','car rental','rent a car'], services:'حجز سيارات، متابعة الطلبات، تجديد التأجير', servicesEn:'Vehicle booking, inquiry follow-up, rental renewals', industries:['Automotive','Retail Motor Vehicles','Consumer Goods Rental','Travel Arrangements'], keywords:['car rental','rent a car','vehicle rental','تأجير سيارات','تاجير سيارات','لتأجير السيارات'] },
  { label:'مراكز صيانة السيارات', en:'Auto repair centers', field:'التجارة والمتاجر', aliases:['مركز صيانة سيارات','ورشة سيارات','auto repair','car service'], services:'حجز صيانة، تذكير بالمواعيد، إعادة استهداف', servicesEn:'Service booking, reminders, retargeting', industries:['Vehicle Repair and Maintenance'] },
  { label:'الفنادق والشاليهات', en:'Hotels and chalets', field:'المطاعم والضيافة', aliases:['فنادق','شاليهات','hotel','chalets'], services:'صفحات حجز، متابعة الاستفسارات، تذكير الحجوزات', servicesEn:'Booking funnels, inquiry follow-up, reservation reminders', industries:['Hotels and Motels','Hospitality'] },
  { label:'مكاتب السياحة والسفر', en:'Travel agencies', field:'المطاعم والضيافة', aliases:['مكتب سياحة','وكالة سفر','travel agency'], services:'جلب طلبات سفر، متابعة واتساب، عروض رحلات', servicesEn:'Travel leads, WhatsApp follow-up, trip offers', industries:['Travel Arrangements'] },
  { label:'المطاعم', en:'Restaurants', field:'المطاعم والضيافة', aliases:['مطعم','restaurants','restaurant'], services:'إعلانات، إدارة العملاء، إعادة العملاء للطلب', servicesEn:'Advertising, CRM, repeat-customer campaigns', industries:['Restaurants'] },
  { label:'شركات البرمجيات', en:'Software companies', field:'التقنية والاتصالات', aliases:['شركة برمجيات','software company','software development'], services:'جلب عملاء شركات، تواصل بالبريد، حجز اجتماعات', servicesEn:'B2B lead generation, email outreach, meeting booking', industries:['Software Development','IT System Custom Software Development'] },
  { label:'وكالات التسويق', en:'Marketing agencies', field:'التسويق والإعلام', aliases:['وكالة تسويق','marketing agency','digital agency'], services:'جلب عملاء، حجز اجتماعات، متابعة العروض', servicesEn:'Lead generation, meeting booking, proposal follow-up', industries:['Marketing Services','Advertising Services'] },
  { label:'وكالات التصميم', en:'Design agencies', field:'التسويق والإعلام', aliases:['وكالة تصميم','design agency','design studio'], services:'تواصل تجاري، جلب مشاريع، أتمتة متابعة المبيعات', servicesEn:'Business outreach, project leads, sales follow-up', industries:['Graphic Design','Design Services'] },
  { label:'شركات الإنتاج', en:'Production companies', field:'التسويق والإعلام', aliases:['شركة إنتاج','إنتاج فيديو','video production','production company'], services:'البحث عن شركات تحتاج تصويرًا ومحتوى', servicesEn:'Prospecting for businesses needing video and content', industries:['Media Production','Movies, Videos, and Sound'] },
  { label:'شركات التوظيف', en:'Recruitment agencies', field:'المال والخدمات المهنية', aliases:['شركة توظيف','recruitment agency','staffing agency'], services:'البحث عن شركات، تواصل تجاري، متابعة احتياجات التوظيف', servicesEn:'Company prospecting, business outreach, hiring follow-up', industries:['Staffing and Recruiting','Executive Search Services'] },
  { label:'متاجر التجارة الإلكترونية', en:'E-commerce stores', field:'التجارة والمتاجر', aliases:['متجر إلكتروني','متاجر الكترونية','ecommerce','e-commerce'], services:'إعلانات، أتمتة البريد والرسائل، استعادة السلات', servicesEn:'Advertising, email and SMS automation, cart recovery', industries:['Online and Mail Order Retail','Internet Marketplace Platforms'] },
  { label:'شركات الجملة والتوزيع', en:'Wholesale and distribution businesses', field:'التجارة والمتاجر', aliases:['شركة توزيع','تجارة الجملة','wholesale','distributor'], services:'البحث عن مشترين شركات، التواصل، متابعة الطلبات', servicesEn:'B2B buyer prospecting, outreach, order follow-up', industries:['Wholesale','Wholesale Import and Export'] },
  { label:'المصانع', en:'Manufacturers', field:'الصناعة والطاقة والنقل', aliases:['مصنع','مصانع','factory','manufacturers'], services:'البحث عن موزعين ومشترين من الشركات', servicesEn:'Distributor and B2B buyer prospecting', industries:['Manufacturing','Industrial Machinery Manufacturing'] },
  { label:'محلات المجوهرات', en:'Jewelry stores', field:'التجارة والمتاجر', aliases:['محل مجوهرات','محلات ذهب','jewelry store','jewellery'], services:'إعلانات، استفسارات واتساب، متابعة المهتمين', servicesEn:'Advertising, WhatsApp leads, inquiry follow-up', industries:['Retail Luxury Goods and Jewelry','Luxury Goods & Jewelry'], keywords:['jewel','jewelry','jewellery','مجوهرات','ذهب'] },
  { label:'منظمو الأعراس', en:'Wedding planners', field:'المطاعم والضيافة', aliases:['منظم أعراس','منظمي الاعراس','wedding planner'], services:'جلب طلبات، حجز استشارات، متابعة الحجوزات', servicesEn:'Lead generation, consultation booking, booking follow-up', industries:['Events Services'], keywords:['wedding','bridal','زفاف','اعراس','أعراس'] },
  { label:'استوديوهات التصوير', en:'Photography studios', field:'التسويق والإعلام', aliases:['استوديو تصوير','مصوريين','photography studio','photographer'], services:'جلب طلبات، حجز جلسات، متابعة العملاء', servicesEn:'Lead generation, session booking, client follow-up', industries:['Photography'] },
  { label:'شركات الأمن والكاميرات', en:'Security and CCTV companies', field:'الصناعة والطاقة والنقل', aliases:['شركة كاميرات','كاميرات مراقبة','cctv','security systems'], services:'جلب عملاء شركات، طلبات معاينة، تواصل تجاري', servicesEn:'B2B lead generation, site visits, business outreach', industries:['Security Systems Services','Security and Investigations'], keywords:['security system','CCTV','surveillance','كاميرات','انظمة امن','أنظمة أمن'] },
  { label:'شركات المسابح', en:'Swimming pool companies', field:'العقارات والبناء', aliases:['شركة مسابح','مسابح','swimming pool company','pool contractor'], services:'طلبات من أصحاب الفلل والمشاريع، حجز معاينات', servicesEn:'Villa and project leads, site visit booking', industries:['Specialty Trade Contractors','Construction'], keywords:['swimming pool','pool construction','pool maintenance','مسابح','مسبح'] },
  { label:'شركات الألمنيوم والزجاج', en:'Aluminum and glass companies', field:'العقارات والبناء', aliases:['ألمنيوم وزجاج','المنيوم','aluminum and glass','aluminium'], services:'جلب مشاريع، تواصل مع المقاولين، طلبات تسعير', servicesEn:'Project leads, contractor outreach, quotation requests', industries:['Glass Product Manufacturing','Architectural and Structural Metal Manufacturing','Building Finishing Contractors'], keywords:['aluminum','aluminium','glass','ألمنيوم','المنيوم','زجاج'] },
  { label:'مورّدو المطاعم', en:'Restaurant suppliers', field:'التجارة والمتاجر', aliases:['موردو المطاعم','مورد مطاعم','restaurant supplier','foodservice supplier'], services:'البحث عن مطاعم وشركات ضيافة، تواصل تجاري', servicesEn:'Restaurant and hospitality prospecting, B2B outreach', industries:['Wholesale Food and Beverage','Wholesale Machinery'], keywords:['restaurant','foodservice','food service','catering equipment','مطاعم','مستلزمات مطاعم','تجهيزات مطاعم'] },
  { label:'مورّدو المعدات الطبية', en:'Medical equipment suppliers', field:'الصحة والطب', aliases:['موردو المعدات الطبية','مورد معدات طبية','medical equipment supplier','medical distributor'], services:'البحث عن عيادات ومستشفيات، تواصل تجاري', servicesEn:'Clinic and hospital prospecting, B2B outreach', industries:['Wholesale Machinery','Medical Device','Medical Equipment Manufacturing'], keywords:['medical','healthcare','dental equipment','معدات طبية','اجهزة طبية','أجهزة طبية'] },
  { label:'شركات الأمن السيبراني', en:'Cybersecurity companies', field:'التقنية والاتصالات', aliases:['أمن سيبراني','الامن السيبراني','cybersecurity','cyber security'], services:'البحث عن عملاء شركات، حجز اجتماعات، متابعة العروض', servicesEn:'B2B prospecting, meeting booking, proposal follow-up', industries:['Computer and Network Security','Data Security Software Products'] },
] as const;

export type Niche = (typeof niches)[number];
export type NicheName = Niche['label'];
export const nicheOf = (label:string) => niches.find(n => n.label === label);
export const knownNiche = (text:string) => niches.find(n => [n.label,n.en,...n.aliases].some(s => norm(s) === norm(text)));
export const nicheKeywords = (label?:string): readonly string[] => {
  const n=nicheOf(label||''); return n && 'keywords' in n ? n.keywords : [];
};
export function findNiches(query:string, field='') {
  const words=norm(query).replace(/[^\p{L}\p{N}]+/gu,' ').trim().split(/\s+/).filter(Boolean);
  return niches.filter(n => (!field || n.field===field) && words.every(w => norm([n.label,n.en,...n.aliases].join(' ')).includes(w)));
}
