'use client';
import { useCallback,useEffect,useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { CheckCircle, Coins, Copy, EnvelopeSimple, LinkSimple, MagnifyingGlass, UsersThree, DownloadSimple, UserPlus, Pause, Play, Key } from '@phosphor-icons/react';
import type { AdminUser } from '@/lib/contracts';
import { api,date,number } from '@/lib/client';
import { Badge,Button,Empty,Field,Forward,Modal,Notice,Open,PageHeading } from './ui';
import { useT } from './lang';
import type { ViewProps } from './platform';

export function AdminDashboard({data}:ViewProps){
  const t=useT(),configured=!!data.provider?.configured,[checking,setChecking]=useState(configured),[check,setCheck]=useState<{credits?:number;low?:boolean;error?:string}|null>(null);
  // Checked on every visit: the connection, and the provider account's credits (red under 200, the email alert's limit).
  const verify=useCallback(()=>api<{credits:number;low:boolean}>('provider/verify',{}).then(r=>r,(e:Error)=>({error:e.message})).then(setCheck).finally(()=>setChecking(false)),[]);
  useEffect(()=>{if(configured)void verify();},[configured,verify]);
  const admin=data.admin!;
  return <><PageHeading title={t('لوحة الإدارة','Admin')}><Link href="/admin/members?invite=1" className="button primary"><UserPlus size={19}/>{t('دعوة مشترك','Invite a member')}</Link></PageHeading>
  <div className="stats-strip">{[{label:t('المشتركون','Members'),value:admin.totals.members??admin.users.length,icon:UsersThree},{label:t('إيميلات مسلّمة','Emails delivered'),value:admin.totals.delivered,icon:EnvelopeSimple},{label:t('كريدت مستهلك','Credits used'),value:admin.totals.used,icon:Coins},{label:t('ملفات منزّلة','Downloads'),value:admin.totals.exports,icon:DownloadSimple}].map(({label,value,icon:Icon})=><div className="stat" key={label}><div className="stat-label"><span>{label}</span><Icon size={20} weight="light"/></div><div className="stat-value">{number(value)}</div></div>)}</div>
  <section className="panel table-panel"><div className="section-title"><h2>{t('المشتركون','Members')}</h2><Link className="text-link" href="/admin/members">{t('عرض الكل','See all')} <Forward/></Link></div><div className="table-scroll"><table><thead><tr><th>{t('المشترك','Member')}</th><th>{t('الرصيد','Credits')}</th><th>{t('الإيميلات','Emails')}</th><th>{t('الحالة','Status')}</th></tr></thead><tbody>{admin.users.slice(0,5).map(u=><tr key={u.id}><td><div className="contact-name"><span className="avatar">{u.name[0]}</span><span><strong>{u.name}</strong><small dir="ltr">{u.email}</small></span></div></td><td>{number(u.balance)}</td><td>{u.leads}</td><td><Badge tone={u.active?'green':'neutral'}>{u.active?t('نشط','Active'):t('معطل','Disabled')}</Badge></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="section-title"><h2>{t('مزوّد البيانات','Data provider')}</h2><Badge tone={data.provider?.configured?'green':'amber'}>{data.provider?.configured?t('مهيأ','Configured'):t('غير مهيأ','Not configured')}</Badge></div>{check?.credits!==undefined&&<div className="balance-callout"><span>{t('رصيد المزوّد','Provider credits')}</span><strong>{number(check.credits)}</strong></div>}{check?.low&&<Notice error>{t('الرصيد قريب من النفاد. اشحنه قبل أن تتوقف عمليات البحث.','Credits are running low. Top up before searches stop.')}</Notice>}<Button variant="secondary" loading={checking} disabled={!configured} onClick={()=>{setChecking(true);void verify();}}>{t('فحص الاتصال','Check the connection')}</Button>{check&&<Notice error={!!check.error}>{check.error??t('الاتصال بمزوّد البيانات يعمل.','The data provider connection works.')}</Notice>}</section>
  <section className="panel"><div className="section-title"><h2>{t('آخر نشاط','Recent activity')}</h2><Link href="/admin/activity" className="text-link">{t('السجل الكامل','Full log')} <Forward/></Link></div>{admin.audit.slice(0,4).map(a=><div className="audit-row" key={a.id}><span className="audit-dot"/><div><strong>{a.action}</strong><p>{a.detail}</p></div><time>{date(a.created_at)}</time></div>)}</section></>;
}

export function MembersView({data,reload,notify}:ViewProps){
  const t=useT(),query=useSearchParams();
  const [inviteOpen,setInviteOpen]=useState(query.get('invite')==='1'),[name,setName]=useState(''),[email,setEmail]=useState(''),[credits,setCredits]=useState(100),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[text,setText]=useState(''),[status,setStatus]=useState('all');
  const [creditUser,setCreditUser]=useState<AdminUser|null>(null),[mode,setMode]=useState<'add'|'set'>('add'),[amount,setAmount]=useState(100),[reason,setReason]=useState(''),[detail,setDetail]=useState<AdminUser|null>(null),[toggleUser,setToggleUser]=useState<AdminUser|null>(null),[resetLink,setResetLink]=useState('');
  const [creditRequestId,setCreditRequestId]=useState(()=>crypto.randomUUID());
  const users=data.admin!.users.filter(u=>(status==='all'||(status==='active')===!!u.active)&&[u.name,u.email].join(' ').toLowerCase().includes(text.toLowerCase()));
  async function invite(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{token:string}>('admin/invite',{name,email,credits});setLink(location.origin+'/invite?token='+result.token);await reload();notify(t('تم إنشاء الدعوة. انسخ الرابط وأرسله.','Invitation created. Copy the link and send it.'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);notify(t('تم نسخ الرابط.','Link copied.'));}catch{notify(t('تعذّر النسخ التلقائي. انسخ الرابط من الحقل.','Could not copy. Copy the link from the field.'),true);}}
  async function changeCredits(e:React.FormEvent){e.preventDefault();if(!creditUser)return;setBusy(true);setError('');try{await api('admin/credits',{userId:creditUser.id,mode,amount,reason,requestId:creditRequestId});await reload();setCreditUser(null);notify(t('تم تعديل الرصيد وتسجيل العملية.','Credits updated and logged.'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function toggle(){if(!toggleUser)return;setBusy(true);try{await api('admin/status',{userId:toggleUser.id,active:!toggleUser.active});await reload();setToggleUser(null);notify(toggleUser.active?t('تم تعطيل الحساب وإنهاء جلساته.','Account disabled and signed out.'):t('تم تفعيل الحساب.','Account enabled.'));}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function reset(){if(!detail)return;setBusy(true);try{const result=await api<{token:string}>('admin/reset',{userId:detail.id});setResetLink(location.origin+'/reset?token='+result.token);await reload();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  const state=(u:AdminUser)=>u.active?t('نشط','Active'):t('معطل','Disabled');
  return <><PageHeading title={t('المشتركون والدعوات','Members and invitations')}><Button onClick={()=>{setInviteOpen(true);setLink('');setError('');}}><UserPlus size={19}/>{t('دعوة مشترك','Invite a member')}</Button></PageHeading>
  <section className="panel table-panel"><div className="table-toolbar"><div className="search-input"><MagnifyingGlass size={19}/><input aria-label={t('ابحث عن مشترك','Search members')} placeholder={t('ابحث بالاسم أو البريد…','Search by name or email…')} value={text} onChange={e=>setText(e.target.value)}/></div><select aria-label={t('الحالة','Status')} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t('كل الحالات','All')}</option><option value="active">{t('نشط','Active')}</option><option value="disabled">{t('معطل','Disabled')}</option></select><span className="result-count">{users.length}</span></div>{users.length?<div className="table-scroll"><table><thead><tr><th>{t('المشترك','Member')}</th><th>{t('الرصيد','Credits')}</th><th>{t('الإيميلات','Emails')}</th><th>{t('عمليات البحث','Searches')}</th><th>{t('الحالة','Status')}</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><button className="contact-name" onClick={()=>{setDetail(u);setResetLink('');}}><span className="avatar">{u.name[0]}</span><span><strong>{u.name}</strong><small dir="ltr">{u.email}</small></span></button></td><td><strong>{number(u.balance)}</strong></td><td>{u.leads}</td><td>{u.searches}</td><td><Badge tone={u.active?'green':'neutral'}>{state(u)}</Badge></td><td><div className="row-actions"><button className="text-button" onClick={()=>{setCreditUser(u);setCreditRequestId(crypto.randomUUID());setAmount(100);setReason('');setMode('add');setError('');}}><Coins size={17}/>{t('الرصيد','Credits')}</button><button className="icon-button" title={u.active?t('تعطيل','Disable'):t('تفعيل','Enable')} aria-label={(u.active?t('تعطيل ','Disable '):t('تفعيل ','Enable '))+u.name} onClick={()=>setToggleUser(u)}>{u.active?<Pause size={18}/>:<Play size={18}/>}</button><button className="icon-button" title={t('التفاصيل','Details')} aria-label={t('تفاصيل ','Details of ')+u.name} onClick={()=>{setDetail(u);setResetLink('');}}><Open/></button></div></td></tr>)}</tbody></table></div>:<Empty title={t('لا يوجد مشتركون بهذه المعايير','No members match')} description={t('عدّل البحث أو أنشئ دعوة جديدة.','Change the search or create an invitation.')}/>}</section>
  <section className="panel table-panel"><div className="section-title"><h2>{t('الدعوات','Invitations')}</h2><Badge>{data.admin!.invitations.length}</Badge></div>{data.admin!.invitations.length?<div className="table-scroll"><table><thead><tr><th>{t('الاسم','Name')}</th><th>{t('البريد','Email')}</th><th>{t('رصيد البداية','Starting credits')}</th><th>{t('تنتهي','Expires')}</th><th>{t('الحالة','Status')}</th></tr></thead><tbody>{data.admin!.invitations.map(i=><tr key={i.id}><td>{i.name}</td><td dir="ltr" className="email-text">{i.email}</td><td>{i.credits}</td><td>{date(i.expires_at)}</td><td><Badge tone={i.used_at?'green':'neutral'}>{i.used_at?t('انضم','Joined'):new Date(i.expires_at)<new Date()?t('منتهية','Expired'):t('بانتظار الانضمام','Pending')}</Badge></td></tr>)}</tbody></table></div>:<Empty title={t('لا توجد دعوات بعد','No invitations yet')} description={t('أنشئ رابط انضمام وحدد رصيد المشترك، ثم انسخه وأرسله.','Create a join link with starting credits, then copy and send it.')}/>}</section>
  {inviteOpen&&<Modal title={link?t('الدعوة جاهزة','Invitation ready'):t('دعوة مشترك جديد','Invite a new member')} onClose={()=>setInviteOpen(false)}>{link?<div className="form-stack"><div className="success-orb"><CheckCircle size={35}/></div><p>{t('الرابط صالح لمدة 48 ساعة، ولم يُرسل أي بريد.','The link is valid for 48 hours; no email was sent.')}</p><Field label={t('رابط الدعوة','Invitation link')}><input dir="ltr" readOnly value={link} onFocus={e=>e.target.select()}/></Field><Button onClick={()=>copy(link)}><Copy size={18}/>{t('نسخ الرابط','Copy link')}</Button></div>:<form className="form-stack" onSubmit={invite}>{error&&<Notice error>{error}</Notice>}<Field label={t('اسم المشترك','Member name')}><input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={60} required/></Field><Field label={t('البريد الإلكتروني','Email')}><input type="email" dir="ltr" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label={t('رصيد البداية','Starting credits')}><input type="number" min={0} max={100000} value={credits} onChange={e=>setCredits(Number(e.target.value))} required/></Field><Button type="submit" loading={busy}><LinkSimple size={18}/>{t('إنشاء رابط الدعوة','Create invitation link')}</Button></form>}</Modal>}
  {creditUser&&<Modal title={t('رصيد ','Credits of ')+creditUser.name} onClose={()=>setCreditUser(null)}><form className="form-stack" onSubmit={changeCredits}><div className="balance-callout"><span>{t('الرصيد الحالي','Current balance')}</span><strong>{creditUser.balance}</strong></div>{error&&<Notice error>{error}</Notice>}<Field label={t('نوع التعديل','Change')}><select value={mode} onChange={e=>{setMode(e.target.value as 'add'|'set');setCreditRequestId(crypto.randomUUID());}}><option value="add">{t('إضافة','Add')}</option><option value="set">{t('تعيين رصيد جديد','Set a new balance')}</option></select></Field><Field label={mode==='add'?t('عدد الكريدت المضاف','Credits to add'):t('الرصيد الجديد','New balance')}><input type="number" min={0} max={100000} value={amount} onChange={e=>{setAmount(Number(e.target.value));setCreditRequestId(crypto.randomUUID());}} required/></Field><Field label={t('السبب','Reason')}><input placeholder={t('مثلًا: تجديد الاشتراك','e.g. subscription renewal')} minLength={3} maxLength={200} value={reason} onChange={e=>{setReason(e.target.value);setCreditRequestId(crypto.randomUUID());}} required/></Field><Notice>{t('الرصيد بعد التعديل: ','Balance after: ')}{mode==='add'?creditUser.balance+amount:amount}</Notice><Button loading={busy} type="submit">{t('تأكيد','Confirm')}</Button></form></Modal>}
  {toggleUser&&<Modal title={toggleUser.active?t('تعطيل الحساب','Disable account'):t('تفعيل الحساب','Enable account')} onClose={()=>setToggleUser(null)}><div className="form-stack"><p>{toggleUser.active?t('سيتوقف وصول '+toggleUser.name+' وتنتهي جلساته. تبقى نتائجه محفوظة.',toggleUser.name+' loses access and is signed out. Their results stay saved.'):t('سيتمكن '+toggleUser.name+' من الدخول واستخدام رصيده.',toggleUser.name+' can sign in and use their credits again.')}</p><Button variant={toggleUser.active?'danger':'primary'} loading={busy} onClick={toggle}>{toggleUser.active?t('تعطيل الحساب','Disable account'):t('تفعيل الحساب','Enable account')}</Button></div></Modal>}
  {detail&&<Modal title={detail.name} onClose={()=>setDetail(null)}><div className="contact-detail"><p dir="ltr">{detail.email}</p><Badge tone={detail.active?'green':'neutral'}>{state(detail)}</Badge><dl><dt>{t('الرصيد','Credits')}</dt><dd>{number(detail.balance)}</dd><dt>{t('الإيميلات','Emails')}</dt><dd>{detail.leads}</dd><dt>{t('عمليات البحث','Searches')}</dt><dd>{detail.searches}</dd><dt>{t('التنزيلات','Downloads')}</dt><dd>{detail.exports}</dd><dt>{t('انضم في','Joined')}</dt><dd>{date(detail.created_at)}</dd></dl>{detail.active&&<Button variant="secondary" loading={busy} onClick={reset}><Key size={18}/>{t('رابط استعادة الوصول','Access recovery link')}</Button>}{resetLink&&<div className="form-stack"><Field label={t('رابط صالح لساعة — لم يُرسل بريد','Valid for one hour — no email sent')}><input readOnly dir="ltr" value={resetLink} onFocus={e=>e.target.select()}/></Field><Button variant="ghost" onClick={()=>copy(resetLink)}>{t('نسخ الرابط','Copy link')} <Copy size={16}/></Button></div>}</div></Modal>}</>;
}
export function ActivityView({data}:ViewProps){
  const t=useT();
  return <><PageHeading title={t('سجل الإدارة','Admin activity')}/><section className="panel">{data.admin!.audit.length?data.admin!.audit.map(a=><div className="audit-row" key={a.id}><span className="audit-dot"/><div><strong>{a.action}</strong><p>{a.detail}</p></div><time>{date(a.created_at)}</time></div>):<Empty title={t('لا يوجد نشاط بعد','No activity yet')} description={t('تظهر إجراءات الإدارة هنا.','Admin actions appear here.')}/>}</section></>;
}
