'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowLeft, ArrowUpLeft, CheckCircle, Coins, Copy, Database, EnvelopeSimple, LinkSimple, MagnifyingGlass, ShieldCheck, UsersThree, DownloadSimple, UserPlus, Pause, Play, Key } from '@phosphor-icons/react';
import type { AdminUser } from '@/lib/contracts';
import { api,date,number } from '@/lib/client';
import { Badge,Button,Empty,Field,Modal,Notice,PageHeading } from './ui';
import type { ViewProps } from './platform';

export function AdminDashboard({data}:ViewProps){
  const [checking,setChecking]=useState(false),[connection,setConnection]=useState('');
  async function verify(){setChecking(true);try{await api('provider/verify',{});setConnection('الاتصال بمزوّد البيانات يعمل.');}catch(e){setConnection((e as Error).message);}finally{setChecking(false);}}
  const admin=data.admin!;
  return <><PageHeading eyebrow="الصورة كاملة، في مكان واحد" title="أهلًا بك في لوحة الإدارة." description="تابع المشتركين واستهلاكهم، وأبقِ تجربة منصتك تحت نظرك."><Link href="/admin/members?invite=1" className="button primary"><UserPlus size={19}/>دعوة مشترك</Link></PageHeading>
  <div className="stats-strip">{[{label:'إجمالي المشتركين',value:admin.totals.members??admin.users.length,unit:(admin.totals.activeMembers??admin.users.filter(u=>u.active).length)+' نشط',icon:UsersThree},{label:'إيميلات تم تسليمها',value:admin.totals.delivered,unit:'بريد محفوظ',icon:EnvelopeSimple},{label:'كريدت مستهلك',value:admin.totals.used,unit:'كريدت',icon:Coins},{label:'عمليات التصدير',value:admin.totals.exports,unit:'ملف CSV',icon:DownloadSimple}].map(({label,value,unit,icon:Icon})=><div className="stat" key={label}><div className="stat-label"><span>{label}</span><Icon size={21} weight="light"/></div><div className="stat-value">{number(value)}<span>{unit}</span></div></div>)}</div>
  <div className="admin-summary-banner"><div className="admin-summary-icon"><ShieldCheck size={36} weight="light"/></div><div><span className="eyebrow">مساحة واضحة لكل مشترك</span><h2>تحكّم في الوصول. تابع كل كريدت.</h2><p>دعوات خاصة، أرصدة مستقلة، وسجل يوثق كل تعديل.</p></div><Link href="/admin/members" className="button secondary">إدارة المشتركين <ArrowLeft size={18}/></Link></div>
  <div className="dashboard-grid"><section className="panel table-panel"><div className="section-title"><div><h2>المشتركون</h2><p>نظرة سريعة على الرصيد والاستخدام.</p></div><Link className="text-link" href="/admin/members">عرض الكل <ArrowLeft size={16}/></Link></div><div className="table-scroll"><table><thead><tr><th>المشترك</th><th>الرصيد</th><th>الإيميلات</th><th>الحالة</th></tr></thead><tbody>{admin.users.slice(0,5).map(u=><tr key={u.id}><td><div className="contact-name"><span className="avatar">{u.name[0]}</span><span><strong>{u.name}</strong><small dir="ltr">{u.email}</small></span></div></td><td>{number(u.balance)}</td><td>{u.leads}</td><td><Badge tone={u.active?'green':'neutral'}>{u.active?'نشط':'معطل'}</Badge></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="section-title"><div><h2>حالة الخدمات</h2><p>الخدمات المتصلة بالمنصة.</p></div></div><div className="service-row"><Database size={23} weight="light"/><div><strong>حفظ الحسابات والرصيد</strong><small>قاعدة البيانات</small></div><Badge tone="green">يعمل</Badge></div><div className="service-row"><UsersThree size={23} weight="light"/><div><strong>مصدر جهات الاتصال</strong><small>آيسي بيز · بحث وإيميلات عمل موثّقة</small></div><Badge tone={data.provider?.configured?'green':'amber'}>{data.provider?.configured?'مهيأ':'غير مهيأ'}</Badge></div><div className="service-row"><EnvelopeSimple size={23} weight="light"/><div><strong>إرسال الدعوات بالبريد</strong><small>نسخ الرابط يدويًا متاح</small></div><Badge>غير متصل</Badge></div></section></div>
  <section className="panel"><Button variant="secondary" loading={checking} disabled={!data.provider?.configured} onClick={verify}>فحص اتصال مزوّد البيانات</Button>{connection&&<Notice>{connection}</Notice>}</section>
  <section className="panel"><div className="section-title"><h2>آخر نشاط إداري</h2><Link href="/admin/activity" className="text-link">السجل الكامل <ArrowLeft size={16}/></Link></div>{admin.audit.slice(0,4).map(a=><div className="audit-row" key={a.id}><span className="audit-dot"/><div><strong>{a.action}</strong><p>{a.detail}</p></div><time>{date(a.created_at)}</time></div>)}</section></>;
}

export function MembersView({data,reload,notify}:ViewProps){
  const query=useSearchParams();
  const [inviteOpen,setInviteOpen]=useState(query.get('invite')==='1'),[name,setName]=useState(''),[email,setEmail]=useState(''),[credits,setCredits]=useState(100),[link,setLink]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[text,setText]=useState(''),[status,setStatus]=useState('all');
  const [creditUser,setCreditUser]=useState<AdminUser|null>(null),[mode,setMode]=useState<'add'|'set'>('add'),[amount,setAmount]=useState(100),[reason,setReason]=useState(''),[detail,setDetail]=useState<AdminUser|null>(null),[toggleUser,setToggleUser]=useState<AdminUser|null>(null),[resetLink,setResetLink]=useState('');
  const [creditRequestId,setCreditRequestId]=useState(()=>crypto.randomUUID());
  const users=data.admin!.users.filter(u=>(status==='all'||(status==='active')===!!u.active)&&[u.name,u.email].join(' ').toLowerCase().includes(text.toLowerCase()));
  async function invite(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{token:string}>('admin/invite',{name,email,credits});setLink(location.origin+'/invite?token='+result.token);await reload();notify('تم إنشاء الدعوة. انسخ الرابط لمشاركته.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value);notify('تم نسخ الرابط.');}catch{notify('تعذّر النسخ التلقائي. يمكنك نسخ الرابط من الحقل.',true);}}
  async function changeCredits(e:React.FormEvent){e.preventDefault();if(!creditUser)return;setBusy(true);setError('');try{await api('admin/credits',{userId:creditUser.id,mode,amount,reason,requestId:creditRequestId});await reload();setCreditUser(null);notify('تم تعديل الرصيد وتسجيل العملية.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function toggle(){if(!toggleUser)return;setBusy(true);try{await api('admin/status',{userId:toggleUser.id,active:!toggleUser.active});await reload();setToggleUser(null);notify(toggleUser.active?'تم تعطيل الحساب وإنهاء جلساته.':'تم تفعيل الحساب.');}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function reset(){if(!detail)return;setBusy(true);try{const result=await api<{token:string}>('admin/reset',{userId:detail.id});setResetLink(location.origin+'/reset?token='+result.token);await reload();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  return <><PageHeading eyebrow="أشخاصك، ومساحتهم" title="المشتركون والدعوات" description="امنح الوصول، وحدد الرصيد، وتابع استخدام كل مشترك."><Button onClick={()=>{setInviteOpen(true);setLink('');setError('');}}><UserPlus size={19}/>دعوة مشترك</Button></PageHeading>
  <section className="panel table-panel"><div className="table-toolbar"><div className="search-input"><MagnifyingGlass size={19}/><input aria-label="البحث عن مشترك" placeholder="ابحث باسم المشترك أو بريده…" value={text} onChange={e=>setText(e.target.value)}/></div><select aria-label="حالة المشترك" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">كل الحالات</option><option value="active">نشط</option><option value="disabled">معطل</option></select><span className="result-count">{users.length} مشترك</span></div>{users.length?<div className="table-scroll"><table><thead><tr><th>المشترك</th><th>الرصيد</th><th>الإيميلات</th><th>عمليات البحث</th><th>الحالة</th><th>إدارة الحساب</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><button className="contact-name" onClick={()=>{setDetail(u);setResetLink('');}}><span className="avatar">{u.name[0]}</span><span><strong>{u.name}</strong><small dir="ltr">{u.email}</small></span></button></td><td><strong>{number(u.balance)}</strong><small>كريدت متاح</small></td><td>{u.leads}</td><td>{u.searches}</td><td><Badge tone={u.active?'green':'neutral'}>{u.active?'نشط':'معطل'}</Badge></td><td><div className="row-actions"><button className="text-button" onClick={()=>{setCreditUser(u);setCreditRequestId(crypto.randomUUID());setAmount(100);setReason('');setMode('add');setError('');}}><Coins size={17}/>الرصيد</button><button className="icon-button" title={u.active?'تعطيل الحساب':'تفعيل الحساب'} aria-label={(u.active?'تعطيل ':'تفعيل ')+u.name} onClick={()=>setToggleUser(u)}>{u.active?<Pause size={18}/>:<Play size={18}/>}</button><button className="icon-button" title="تفاصيل المشترك" aria-label={'تفاصيل '+u.name} onClick={()=>{setDetail(u);setResetLink('');}}><ArrowUpLeft size={18}/></button></div></td></tr>)}</tbody></table></div>:<Empty title="لا يوجد مشتركون بهذه المعايير" description="عدّل البحث أو أنشئ دعوة جديدة."/>}</section>
  <section className="panel table-panel"><div className="section-title"><div><h2>الدعوات</h2><p>رابط خاص لكل شخص، صالح لمدة 48 ساعة.</p></div><Badge>{data.admin!.invitations.length} دعوة</Badge></div>{data.admin!.invitations.length?<div className="table-scroll"><table><thead><tr><th>الاسم</th><th>البريد</th><th>رصيد البداية</th><th>تنتهي في</th><th>الحالة</th></tr></thead><tbody>{data.admin!.invitations.map(i=><tr key={i.id}><td>{i.name}</td><td dir="ltr" className="email-text">{i.email}</td><td>{i.credits}</td><td>{date(i.expires_at)}</td><td><Badge tone={i.used_at?'green':'neutral'}>{i.used_at?'تم الانضمام':new Date(i.expires_at)<new Date()?'منتهية':'بانتظار الانضمام'}</Badge></td></tr>)}</tbody></table></div>:<Empty title="دعوتك الأولى تبدأ هنا" description="أنشئ رابط انضمام وحدد رصيد المشترك. الإرسال الآلي بالبريد غير متصل حاليًا؛ انسخ الرابط وأرسله."/>}</section>
  {inviteOpen&&<Modal title={link?'الدعوة جاهزة':'دعوة مشترك جديد'} onClose={()=>setInviteOpen(false)}>{link?<div className="form-stack"><div className="success-orb"><CheckCircle size={35}/></div><p>تم تجهيز دعوة {name}. الرابط صالح لمدة 48 ساعة؛ لم يتم إرسال بريد إلكتروني.</p><Field label="رابط الدعوة"><input dir="ltr" readOnly value={link} onFocus={e=>e.target.select()}/></Field><Button onClick={()=>copy(link)}><Copy size={18}/>نسخ رابط الدعوة</Button><a href={link} target="_blank" rel="noreferrer" className="text-link">فتح رابط الدعوة <ArrowUpLeft size={17}/></a></div>:<form className="form-stack" onSubmit={invite}>{error&&<Notice error>{error}</Notice>}<Field label="اسم المشترك"><input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={60} required/></Field><Field label="البريد الإلكتروني"><input type="email" dir="ltr" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="رصيد البداية" hint="يمكن تغييره لاحقًا لكل مشترك."><input type="number" min={0} max={100000} value={credits} onChange={e=>setCredits(Number(e.target.value))} required/></Field><Notice>سيتم إنشاء رابط تنسخه يدويًا. الإرسال الآلي غير متصل.</Notice><Button type="submit" loading={busy}><LinkSimple size={18}/>إنشاء رابط الدعوة</Button></form>}</Modal>}
  {creditUser&&<Modal title={'رصيد '+creditUser.name} onClose={()=>setCreditUser(null)}><form className="form-stack" onSubmit={changeCredits}><div className="balance-callout"><span>الرصيد الحالي</span><strong>{creditUser.balance} <small>كريدت</small></strong></div>{error&&<Notice error>{error}</Notice>}<Field label="نوع التعديل"><select value={mode} onChange={e=>{setMode(e.target.value as 'add'|'set');setCreditRequestId(crypto.randomUUID());}}><option value="add">إضافة إلى الرصيد</option><option value="set">تعيين رصيد جديد / تصفير</option></select></Field><Field label={mode==='add'?'عدد الكريدت المضاف':'الرصيد الجديد'}><input type="number" min={0} max={100000} value={amount} onChange={e=>{setAmount(Number(e.target.value));setCreditRequestId(crypto.randomUUID());}} required/></Field><Field label="سبب التعديل"><input placeholder="مثلًا: تجديد حصة المشترك" minLength={3} maxLength={200} value={reason} onChange={e=>{setReason(e.target.value);setCreditRequestId(crypto.randomUUID());}} required/></Field><Notice>الرصيد بعد التعديل: {mode==='add'?creditUser.balance+amount:amount} كريدت. ستُحفظ العملية في سجل الإدارة.</Notice><Button loading={busy} type="submit">تأكيد تعديل الرصيد</Button></form></Modal>}
  {toggleUser&&<Modal title={toggleUser.active?'تعطيل حساب المشترك':'تفعيل حساب المشترك'} onClose={()=>setToggleUser(null)}><div className="form-stack"><p>{toggleUser.active?'سيتوقف وصول '+toggleUser.name+' إلى المنصة، وتنتهي جلساته الحالية. تبقى نتائجه وسجلاته محفوظة.':'سيتمكن '+toggleUser.name+' من تسجيل الدخول واستخدام رصيده المتبقي.'}</p><Button variant={toggleUser.active?'danger':'primary'} loading={busy} onClick={toggle}>{toggleUser.active?'تعطيل الحساب':'تفعيل الحساب'}</Button></div></Modal>}
  {detail&&<Modal title="تفاصيل المشترك" onClose={()=>setDetail(null)}><div className="contact-detail"><span className="avatar avatar-large">{detail.name[0]}</span><h3>{detail.name}</h3><p dir="ltr">{detail.email}</p><Badge tone={detail.active?'green':'neutral'}>{detail.active?'حساب نشط':'حساب معطل'}</Badge><dl><dt>الرصيد</dt><dd>{number(detail.balance)} كريدت</dd><dt>الإيميلات المسلّمة</dt><dd>{detail.leads}</dd><dt>عمليات البحث</dt><dd>{detail.searches}</dd><dt>عمليات التصدير</dt><dd>{detail.exports}</dd><dt>تاريخ الانضمام</dt><dd>{date(detail.created_at)}</dd></dl>{detail.active&&<Button variant="secondary" loading={busy} onClick={reset}><Key size={18}/>إنشاء رابط استعادة الوصول</Button>}{resetLink&&<div className="form-stack"><Field label="رابط صالح لساعة واحدة — لم يتم إرسال بريد"><input readOnly dir="ltr" value={resetLink} onFocus={e=>e.target.select()}/></Field><Button variant="ghost" onClick={()=>copy(resetLink)}>نسخ الرابط <Copy size={16}/></Button></div>}</div></Modal>}</>;
}
export function ActivityView({data}:ViewProps){
  return <><PageHeading eyebrow="سجل واضح لكل إجراء" title="نشاط الإدارة" description="الدعوات وتغييرات الأرصدة وحالات الحسابات، مع وقت كل عملية."/><section className="panel">{data.admin!.audit.length?data.admin!.audit.map(a=><div className="audit-row" key={a.id}><span className="audit-dot"/><div><strong>{a.action}</strong><p>{a.detail}</p></div><time>{date(a.created_at)}</time></div>):<Empty title="لا يوجد نشاط بعد" description="تظهر إجراءات الإدارة هنا فور حدوثها."/>}</section></>;
}
