'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import type { Contact } from '@/lib/contracts';
import type { CrmState } from '@/lib/crm';
import { api,downloadContacts,number } from '@/lib/client';
import type { ViewProps } from './platform';
import { Button,Field,Modal,Notice,PageHeading,Empty } from './ui';
import { useT } from './lang';
const stageNames=[['new','جديد','New'],['contacted','تم التواصل','Contacted'],['replied','ردّ','Replied'],['interested','مهتم','Interested'],['not_fit','غير مناسب','Not a fit']];
const columns=[['name','الاسم','Name'],['email','البريد','Email'],['company','الشركة','Company'],['title','المنصب','Title'],['city','المدينة','City'],['country','الدولة','Country'],['website','الموقع','Website'],['kind','نوع العميل','Contact type'],['stage','المرحلة','Stage'],['tags','الوسوم','Tags'],['notes','الملاحظات','Notes']];
export function CrmView({data,notify,reload}:ViewProps){
  const t=useT(),[state,setState]=useState<CrmState|null>(null),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false);
  const [text,setText]=useState(''),[stage,setStage]=useState(''),[list,setList]=useState(''),[page,setPage]=useState(1),[tag,setTag]=useState('');
  const [selected,setSelected]=useState<string[]>([]),[edit,setEdit]=useState<Contact|null>(null),[draft,setDraft]=useState({stage:'new',tags:'',notes:'',lists:[] as string[]});
  const [listName,setListName]=useState(''),[exclusion,setExclusion]=useState(''),[exporting,setExporting]=useState(false),[preview,setPreview]=useState(''),[profile,setProfile]=useState<'generic'|'gohighlevel'>('generic'),[chosen,setChosen]=useState(['name','email','company','title','city','country']);
  useEffect(()=>{let active=true;api<CrmState>('crm').then(s=>{if(active)setState(s);}).catch(e=>{if(active)setFailure(e.message);});return()=>{active=false;};},[]);
  async function action(path:string,body:unknown){setBusy(true);try{await api(path,body);setState(await api<CrmState>('crm'));await reload();notify(t('تم الحفظ.','Saved.'));return true;}catch(e){notify((e as Error).message,true);return false;}finally{setBusy(false);}}
  if(failure)return <Notice error>{failure}</Notice>;
  if(!state)return <p role="status">{t('نحمّل إدارة العملاء…','Loading CRM…')}</p>;
  const metadata=new Map(state.meta.map(m=>[m.contact_id,m]));
  const rows=data.contacts.filter(c=>{const m=metadata.get(c.id);return (!stage||(m?.stage||'new')===stage)&&(!list||m?.lists.includes(list))&&(!tag||m?.tags.some(s=>s.toLowerCase().includes(tag.toLowerCase())))&&[c.name,c.company,c.email,m?.notes,...(m?.tags||[])].join(' ').toLowerCase().includes(text.toLowerCase());});
  const pages=Math.max(1,Math.ceil(rows.length/25)),current=Math.min(page,pages),visible=rows.slice((current-1)*25,current*25);
  const exportOptions={...(selected.length?{ids:selected}: {ids:rows.slice(0,1000).map(c=>c.id)}),profile,columns:chosen};
  function open(c:Contact){const m=metadata.get(c.id);setDraft({stage:m?.stage||'new',tags:(m?.tags||[]).join(', '),notes:m?.notes||'',lists:m?.lists||[]});setEdit(c);}
  return <><PageHeading title={t('إدارة العملاء','CRM')} description={t('رتّب العملاء وتابع التواصل. ملاحظاتك وقوائمك خاصة بحسابك.','Organize contacts and follow up. Your notes and lists are private.')}><Button variant="secondary" disabled={!rows.length} onClick={()=>{setPreview('');setExporting(true);}}>{t('تصدير مخصص','Custom export')}</Button></PageHeading>
  <section className="panel crm-section"><div className="crm-filters"><Field label={t('بحث','Search')}><input value={text} onChange={e=>{setText(e.target.value);setPage(1);}} placeholder={t('اسم، شركة، بريد أو ملاحظة','Name, company, email or note')}/></Field><Field label={t('المرحلة','Stage')}><select aria-label={t('المرحلة','Stage')} value={stage} onChange={e=>{setStage(e.target.value);setPage(1);}}><option value="">{t('الكل','All')}</option>{stageNames.map(([key,ar,en])=><option key={key} value={key}>{t(ar,en)}</option>)}</select></Field><Field label={t('القائمة','List')}><select aria-label={t('القائمة','List')} value={list} onChange={e=>{setList(e.target.value);setPage(1);}}><option value="">{t('الكل','All')}</option>{state.lists.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Field label={t('وسم','Tag')}><input value={tag} onChange={e=>{setTag(e.target.value);setPage(1);}}/></Field></div>
  <p>{number(rows.length)} {t('عميل','contacts')} · {selected.length} {t('محدد','selected')}</p>
  {rows.length?<><div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label={t('تحديد الصفحة','Select page')} checked={visible.every(c=>selected.includes(c.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(c=>c.id)])]:selected.filter(id=>!visible.some(c=>c.id===id)))}/></th><th>{t('العميل','Contact')}</th><th>{t('النوع','Type')}</th><th>{t('المرحلة','Stage')}</th><th>{t('الوسوم','Tags')}</th></tr></thead><tbody>{visible.map(c=>{const m=metadata.get(c.id),s=stageNames.find(([key])=>key===(m?.stage||'new'))!;return <tr key={c.id}><td><input type="checkbox" aria-label={t('تحديد ','Select ')+c.email} checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/></td><td><button className="text-link" onClick={()=>open(c)}>{c.name||c.company}</button><small dir="ltr">{c.email}</small></td><td>{c.kind==='company'?t('شركة','Company'):t('شخص','Person')}</td><td>{t(s[1],s[2])}</td><td>{m?.tags.join('، ')||'—'}</td></tr>;})}</tbody></table></div><div className="pagination"><span>{current}/{pages}</span><Button variant="ghost" disabled={current===1} onClick={()=>setPage(current-1)}>{t('السابق','Previous')}</Button><Button variant="ghost" disabled={current===pages} onClick={()=>setPage(current+1)}>{t('التالي','Next')}</Button></div></>:<Empty title={t('لا يوجد عملاء بهذه المعايير','No matching contacts')} description={t('غيّر الفلاتر أو ابدأ بحثًا جديدًا.','Change filters or start a search.')}/>}
  </section>
  <div className="settings-grid crm-section"><section className="panel"><h2>{t('القوائم','Lists')}</h2><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await action('crm/list',{name:listName}))setListName('');}}><Field label={t('اسم القائمة','List name')}><input value={listName} onChange={e=>setListName(e.target.value)} maxLength={80} required/></Field><Button loading={busy} type="submit">{t('إضافة قائمة','Add list')}</Button></form>{state.lists.map(l=><div className="crm-item" key={l.id}><span>{l.name}</span><Button variant="ghost" disabled={busy} onClick={()=>void action('crm/remove',{id:l.id,kind:'list'})}>{t('إزالة القائمة','Remove list')}</Button></div>)}</section>
  <section className="panel"><h2>{t('الجماهير المحفوظة','Saved audiences')}</h2><p>{t('احفظ المعايير من صفحة البحث لتستخدمها مجددًا.','Save criteria from the search page to reuse them.')}</p>{state.audiences.map(a=><div className="crm-item" key={a.id}><Link className="text-link" href={'/search?saved='+encodeURIComponent(JSON.stringify(a.filters))}>{a.name}</Link><Button variant="ghost" disabled={busy} onClick={()=>void action('crm/remove',{id:a.id,kind:'audience'})}>{t('إزالة','Remove')}</Button></div>)}</section>
  <section className="panel"><h2>{t('قائمة الاستبعاد','Exclusions')}</h2><p>{t('لن تستلم نتائج جديدة لهذه الإيميلات والنطاقات.','New deliveries exclude these emails and domains.')}</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await action('crm/exclude',{value:exclusion}))setExclusion('');}}><Field label={t('بريد أو نطاق','Email or domain')}><input dir="ltr" value={exclusion} onChange={e=>setExclusion(e.target.value)} placeholder="example.com" required maxLength={254}/></Field><Button loading={busy} type="submit">{t('استبعاد','Exclude')}</Button></form>{state.exclusions.map(e=><div className="crm-item" key={e.value}><span dir="ltr">{e.value}</span><Button variant="ghost" disabled={busy} onClick={()=>void action('crm/exclude',{value:e.value,remove:true})}>{t('إزالة','Remove')}</Button></div>)}</section>
  <section className="panel"><h2>{t('إشعارات البحث','Search notifications')}</h2>{!state.notifications.length&&<p>{t('تظهر هنا عمليات البحث المكتملة.','Completed searches appear here.')}</p>}{state.notifications.map(n=><div className="crm-item" key={n.id}><Link className="text-link" href={'/leads?search='+n.search_id}>{n.message}</Link>{!n.read_at&&<Button variant="ghost" disabled={busy} onClick={()=>void action('crm/read',{id:n.id})}>{t('تمت القراءة','Mark read')}</Button>}</div>)}<h3>{t('طلبات الحذف','Deletion requests')}</h3>{state.deletions.map(d=><p key={d.id}>{d.email||t('بيانات محذوفة','Deleted data')} · {d.status==='pending'?t('بانتظار مراجعة المالك','Awaiting owner review'):t('تم الحذف','Deleted')}</p>)}</section></div>
  {edit&&<Modal title={edit.name||edit.company} onClose={()=>setEdit(null)}><form className="form-stack" onSubmit={async e=>{e.preventDefault();if(await action('crm/contact',{contactId:edit.id,...draft,tags:draft.tags.split(/[,،]/).map(s=>s.trim()).filter(Boolean)}))setEdit(null);}}><p dir="ltr">{edit.email}</p><Field label={t('مرحلة التواصل','Contact stage')}><select aria-label={t('مرحلة التواصل','Contact stage')} value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value})}>{stageNames.map(([key,ar,en])=><option key={key} value={key}>{t(ar,en)}</option>)}</select></Field><Field label={t('وسوم مفصولة بفاصلة','Comma separated tags')}><input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})}/></Field><Field label={t('ملاحظات خاصة','Private notes')}><textarea maxLength={4000} rows={4} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></Field><fieldset><legend>{t('القوائم','Lists')}</legend>{state.lists.map(l=><label className="check-label" key={l.id}><input type="checkbox" checked={draft.lists.includes(l.id)} onChange={e=>setDraft({...draft,lists:e.target.checked?[...draft.lists,l.id]:draft.lists.filter(id=>id!==l.id)})}/>{l.name}</label>)}</fieldset><Button loading={busy} type="submit">{t('حفظ','Save')}</Button><Button variant="ghost" disabled={busy} type="button" onClick={()=>void action('crm/delete-request',{contactId:edit.id})}>{t('طلب حذف البيانات من المنصة','Request deletion from the platform')}</Button></form></Modal>}
  {exporting&&<Modal title={t('تجهيز التصدير','Prepare export')} onClose={()=>setExporting(false)}><div className="form-stack"><Field label={t('قالب التصدير','Export profile')}><select aria-label={t('قالب التصدير','Export profile')} value={profile} onChange={e=>{setProfile(e.target.value as typeof profile);if(e.target.value==='gohighlevel')setChosen(c=>c.includes('email')?c:[...c,'email']);setPreview('');}}><option value="generic">{t('عام','Generic')}</option><option value="gohighlevel">GoHighLevel</option></select></Field><fieldset><legend>{t('الأعمدة','Columns')}</legend>{columns.map(([key,ar,en])=><label className="check-label" key={key}><input type="checkbox" disabled={profile==='gohighlevel'&&key==='email'} checked={chosen.includes(key)} onChange={e=>{setChosen(e.target.checked?[...chosen,key]:chosen.filter(k=>k!==key));setPreview('');}}/>{t(ar,en)}</label>)}</fieldset><p>{selected.length||Math.min(rows.length,1000)} {t('صف · دون خصم إضافي','rows · no extra charge')}</p>{!selected.length&&rows.length>1000&&<Notice>{t('التصدير المخصص محدود بأول 1000 نتيجة مطابقة.','Custom export is limited to the first 1,000 matching results.')}</Notice>}<Button variant="secondary" disabled={!chosen.length||busy} onClick={async()=>{setBusy(true);try{const r=await api<{preview:string}>('export/preview',exportOptions);setPreview(r.preview);}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}>{t('معاينة أول خمسة صفوف','Preview first five rows')}</Button>{preview&&<pre className="crm-preview" dir="ltr">{preview}</pre>}<Button loading={busy} disabled={!chosen.length} onClick={async()=>{setBusy(true);try{await downloadContacts(exportOptions);await reload();setExporting(false);}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}>{t('تنزيل CSV','Download CSV')}</Button></div></Modal>}
  </>;
}
type Ops={counts:{fetched:number;submitted:number;catalog:number;reused:number;delivered:number};reuseEnabled:boolean;estimatedCost:number|null;modeledValue:number|null;modeledMargin:number|null;deletions:CrmState['deletions']};
export function CrmOperations({notify,reload}:ViewProps){
  const t=useT(),[state,setState]=useState<Ops|null>(null),[failure,setFailure]=useState(''),[review,setReview]=useState<CrmState['deletions'][number]|null>(null),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;api<Ops>('admin/crm').then(s=>{if(active)setState(s);}).catch(e=>{if(active)setFailure(e.message);});return()=>{active=false;};},[]);
  if(failure)return <Notice error>{failure}</Notice>;if(!state)return <p role="status">{t('نحمّل العمليات…','Loading operations…')}</p>;
  return <><PageHeading title={t('عمليات العملاء','Contact operations')}/><Notice>{state.reuseEnabled?t('إعادة الاستخدام بين الحسابات مفعلة.','Cross-account reuse is enabled.'):t('إعادة الاستخدام بين الحسابات معطلة.','Cross-account reuse is disabled.')}</Notice><div className="credit-overview crm-section">{Object.entries(state.counts).map(([key,value])=><div key={key}><span>{({fetched:t('سجلات جُلبت','Fetched'),submitted:t('أُرسلت للتحقق','Submitted'),catalog:t('المخزون','Catalog'),reused:t('تسليم من المخزون','Catalog deliveries'),delivered:t('الإيميلات المسلّمة','Delivered emails')} as Record<string,string>)[key]}</span><strong>{number(value)}</strong></div>)}</div><section className="panel crm-section"><h2>{t('تقديرات التكلفة والقيمة','Cost and value estimates')}</h2><p>{t('هذه سيناريوهات حسب الأسعار المضبوطة، وليست إيرادات محصلة أو أرباحًا فعلية. التحقق المحسوب يشمل المحاولات التي لم تُنتج بريدًا.','These are configured-rate scenarios, not collected revenue or actual profit. Submissions include attempts that found no email.')}</p>{[['التكلفة التقديرية','Estimated cost',state.estimatedCost],['القيمة حسب سعر الكريدت','Credit-rate value',state.modeledValue],['الهامش التقديري','Modeled margin',state.modeledMargin]].map(([ar,en,value])=><p key={String(en)}>{t(String(ar),String(en))}: {value===null?t('لم تُضبط الأسعار','Rates not configured'):'$'+Number(value).toFixed(2)}</p>)}</section><section className="panel"><h2>{t('طلبات حذف تنتظر المراجعة','Pending deletion requests')}</h2>{state.deletions.map(d=><div className="crm-item" key={d.id}><span dir="ltr">{d.email}</span><Button variant="secondary" onClick={()=>setReview(d)}>{t('مراجعة','Review')}</Button></div>)}</section>{review&&<Modal title={t('مراجعة حذف البيانات','Review data deletion')} onClose={()=>setReview(null)}><p dir="ltr">{review.email}</p><Notice error>{t('سيُحذف هذا البريد وبياناته من المخزون ومن نتائج جميع الحسابات، ويُمنع تسليمه مجددًا. يبقى سجل الرصيد دون استرجاع تلقائي.','This email and its data will be deleted from the catalog and every account, and blocked from future delivery. Credit history is retained without an automatic refund.')}</Notice><Button variant="danger" loading={busy} onClick={async()=>{setBusy(true);try{await api('admin/crm/delete',{id:review.id});setReview(null);setState(await api<Ops>('admin/crm'));await reload();notify(t('تم الحذف وسُجلت العملية.','Deleted and audited.'));}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}>{t('اعتماد وتنفيذ الحذف','Approve and delete')}</Button></Modal>}</>;
}
