'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter,useSearchParams } from 'next/navigation';
import { ArrowLeft, ArrowUpLeft, ArrowDown, Check, CheckCircle, Coins, Copy, DownloadSimple, EnvelopeSimple, MagnifyingGlass, MapPin, Plus, SlidersHorizontal, Sparkle, Target, UsersThree, ClockCounterClockwise, Buildings, ArrowSquareOut } from '@phosphor-icons/react';
import { Contact, countries, Search, SearchInput, sectors } from '@/lib/contracts';
import { api,date,downloadContacts,number } from '@/lib/client';
import type { ViewProps } from './platform';
import { SearchProgress } from './search-progress';
import { Badge,Button,Empty,Field,Modal,Notice,PageHeading } from './ui';

export function Dashboard({data}:ViewProps) {
  const counts=data.summary?data.summary.weekly.map(d=>({day:new Intl.DateTimeFormat('ar',{weekday:'short'}).format(new Date(d.start)),n:d.count})):Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return {day:new Intl.DateTimeFormat('ar',{weekday:'short'}).format(d),n:data.contacts.filter(c=>new Date(c.created_at).toDateString()===d.toDateString()).length};});
  const max=Math.max(1,...counts.map(x=>x.n));
  return <>
    <PageHeading eyebrow="مساحتك، وفرصك القادمة" title={'أهلًا '+data.user.name.split(' ')[0]+'، يوم جديد للفرص.'} description="من جمهور واضح إلى قائمة جاهزة للتواصل. كل شيء يبدأ من هنا."><Link href="/search" className="button primary"><Plus size={19}/><span>بحث جديد</span></Link></PageHeading>
    <div className="stats-strip">{[{label:'رصيدك المتاح',value:data.user.balance,unit:'كريدت',icon:Coins},{label:'جهات اتصال محفوظة',value:data.summary?.contacts??data.contacts.length,unit:'بريد جديد',icon:UsersThree},{label:'عمليات البحث',value:data.summary?.searches??data.searches.length,unit:'بحث',icon:MagnifyingGlass},{label:'الملفات المنزّلة',value:data.summary?.exports??data.exports.length,unit:'ملف CSV',icon:DownloadSimple}].map(({label,value,unit,icon:Icon})=><div className="stat" key={label}><div className="stat-label"><span>{label}</span><Icon size={21} weight="light"/></div><div className="stat-value">{number(value)}<span>{unit}</span></div></div>)}</div>
    <section className="hero-panel"><div className="hero-copy"><span className="hero-eyebrow"><Sparkle size={16}/> خطوة أقرب إلى العميل المناسب</span><h2>أنت تعرف خدمتك.<br/><span>لنجد من يحتاجها.</span></h2><p>حدد المجال والمكان، أو ابدأ بوصف بسيط لجمهورك.<br/>سنرتب لك البحث، وأنت تختار خطوتك التالية.</p><Link href="/search" className="button light"><span>ابدأ البحث عن عملائك</span><span className="button-icon"><ArrowUpLeft size={19}/></span></Link></div><div className="hero-art" aria-hidden="true"><div className="hero-ring"/><div className="hero-ring second"/><div className="target-node"><Target size={38} weight="light"/></div><div className="mini-contact mini-one"><span className="avatar mint">خ ح</span><div><strong>العميل المناسب</strong><small>يبدأ بمعايير واضحة</small></div><CheckCircle size={17}/></div><div className="mini-contact mini-two"><span className="avatar sand"><Buildings size={23}/></span><div><strong>مجالات متعددة</strong><small>فرص تناسب ما تقدمه</small></div></div><div className="mini-tag"><span className="tiny-dot"/> قائمة منظمة وجاهزة</div></div></section>
    <div className="dashboard-grid"><section className="panel"><div className="section-title"><div><h2>آخر عمليات البحث</h2><p>عد إلى حيث توقفت.</p></div><Link className="text-link" href="/history">عرض الكل <ArrowLeft size={16}/></Link></div>{data.searches.length?<div className="recent-list">{data.searches.slice(0,4).map(s=><Link key={s.id} href={'/leads?search='+s.id} className="recent-row"><span className="recent-icon"><MagnifyingGlass size={23} weight="light"/></span><div><strong>{s.title}</strong><small>{date(s.created_at)}</small></div><div className="recent-result"><strong>{s.delivered} <small>بريد جديد</small></strong><span>{s.duplicates?'تم استبعاد '+s.duplicates+' مكرر':'نتائج محفوظة في حسابك'}</span></div><ArrowLeft size={18}/></Link>)}</div>:<Empty title="قائمتك الأولى تبدأ ببحث" description="حدد جمهورك لنحفظ النتائج هنا."><Link href="/search" className="text-link">ابدأ الآن <ArrowLeft size={15}/></Link></Empty>}<div className="panel-foot"><CheckCircle size={17}/><span>البريد المحفوظ لا يُخصم منك مرة ثانية.</span></div></section>
    <section className="panel activity-panel"><div className="section-title"><div><h2>نشاطك هذا الأسبوع</h2><p>جهات الاتصال التي أضفتها.</p></div><span className="small-icon"><ArrowUpLeft size={21}/></span></div><div className="activity-total">{counts.reduce((a,c)=>a+c.n,0)} <span>بريد جديد</span></div><div className="bar-chart" role="img" aria-label={counts.map(c=>c.day+': '+c.n).join('، ')}>{counts.map((c,i)=><div className="chart-column" key={i}><div className="bar-space"><span className={c.n?'bar filled':'bar'} style={{height:(c.n?Math.max(8,c.n/max*88):3)+'%'}} title={c.n+' بريد'}/></div><small>{c.day}</small></div>)}</div></section></div>
    <div className="journey-panel"><span className="journey-label">خطوتك القادمة</span><div><span className="step-number">01</span><strong>حدد الجمهور</strong><small>اختر من تريد الوصول إليه</small></div><ArrowLeft size={20}/><div><span className="step-number">02</span><strong>راجع النتائج</strong><small>كل بريد جديد محفوظ لك</small></div><ArrowLeft size={20}/><div><span className="step-number">03</span><strong>نزّل قائمتك</strong><small>وارفعها إلى GoHighLevel</small></div></div>
  </>;
}

export function SearchView({data,reload,notify}:ViewProps){
  const router=useRouter(),query=useSearchParams();
  const previous=data.searches.find(s=>s.id===query.get('from'));
  const initial:Partial<SearchInput>=previous?JSON.parse(previous.filters):{};
  const [mode,setMode]=useState<'manual'|'ai'>('manual'),[description,setDescription]=useState(''),[suggesting,setSuggesting]=useState(false),[suggested,setSuggested]=useState(false),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[error,setError]=useState('');
  const [requestId,setRequestId]=useState(()=>crypto.randomUUID());
  const [filters,setFilters]=useState({sector:initial.sector||sectors[0],country:initial.country||countries[0],city:initial.city||'',title:initial.title||'',size:initial.size||'all',count:Math.min(initial.count||10,data.provider?.maxCount??50)});
  function change(key:string,value:string|number){setFilters(f=>({...f,[key]:value}));setConfirmed(false);setRequestId(crypto.randomUUID());}
  async function suggest(){setSuggesting(true);setError('');try{const result=await api<typeof filters>('assistant',{description});setFilters(result);setSuggested(true);setConfirmed(false);setRequestId(crypto.randomUUID());}catch(e){setError((e as Error).message);}finally{setSuggesting(false);}}
  async function submit(e:React.FormEvent){
    e.preventDefault();setBusy(true);setError('');
    try{
      const result=await api<Search>('search',{...filters,confirmed,requestId});
      await reload();
      if(['failed','unknown'].includes(result.status)){
        setError((result.message || 'تعذّر إكمال الطلب.')+' لم يُخصم كريدت من المنصة. راجع سجل FullEnrich قبل إنشاء بحث جديد.');
        return;
      }
      notify(result.status==='awaiting_provider'?'تم إرسال الطلب إلى FullEnrich. نتابع تجهيز الإيميلات.':result.delivered?'تم حفظ '+result.delivered+' بريد جديد.':'لم نجد إيميلات جديدة قابلة للتسليم في هذه الدفعة.');
      router.push('/leads?search='+result.id);
    }catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <><PageHeading eyebrow="اكتشف فرصتك التالية" title="من تريد الوصول إليه؟" description="ابدأ بمعايير واضحة. يمكنك تعديل جمهورك في كل بحث."/>
  <div className="search-layout"><section className="panel search-panel"><div className="mode-tabs" role="tablist" aria-label="طريقة الاستهداف"><button role="tab" aria-selected={mode==='manual'} className={mode==='manual'?'selected':''} onClick={()=>setMode('manual')}><SlidersHorizontal size={20}/>حدد المعايير بنفسك</button><button role="tab" aria-selected={mode==='ai'} className={mode==='ai'?'selected':''} onClick={()=>setMode('ai')}><Sparkle size={20}/>مساعد الاستهداف</button></div>
  {mode==='ai'&&<div className="assistant-box"><div className="assistant-heading"><span className="small-icon"><Sparkle size={23}/></span><div><h3>صف خدمتك وعميلك المثالي</h3><p>سنقترح نقطة بداية، وأنت تراجع المعايير.</p></div><Badge tone="amber">محاكاة محلية</Badge></div><textarea aria-label="وصف النشاط والجمهور" value={description} onChange={e=>setDescription(e.target.value)} placeholder="مثلًا: أقدم خدمات تسويق وأبحث عن شركات عقارية في دبي…" rows={3}/><div className="assistant-bottom"><small>اقتراح بالكلمات المفتاحية للتجربة؛ AI الحقيقي غير متصل.</small><Button variant="secondary" loading={suggesting} disabled={description.trim().length<8} onClick={suggest}>اقتراح المعايير <Sparkle size={16}/></Button></div>{suggested&&<Notice>جهزنا اقتراحًا. راجع الحقول أدناه قبل البحث.</Notice>}</div>}
  <form onSubmit={submit}><div className="form-section"><div className="section-label"><span>01</span><h3>الجمهور المستهدف</h3></div><div className="form-grid"><Field label="مجال العمل"><select value={filters.sector} onChange={e=>change('sector',e.target.value)}>{sectors.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="حجم الشركة"><select value={filters.size} onChange={e=>change('size',e.target.value)}><option value="all">كل الأحجام</option><option value="1-10">1–10 موظفين</option><option value="11-50">11–50 موظفًا</option><option value="51-200">51–200 موظف</option></select></Field><Field label="البلد"><select value={filters.country} onChange={e=>change('country',e.target.value)}>{countries.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="المدينة" hint="موقع الشخص؛ اتركها فارغة للبلد كاملًا. اكتب المدن بالإنجليزية."><input value={filters.city} onChange={e=>change('city',e.target.value)} placeholder="مثلًا: الرياض" maxLength={60}/></Field><Field label="المسمى الوظيفي" hint="اختياري — بالإنجليزية مثل Marketing Director"><input value={filters.title} onChange={e=>change('title',e.target.value)} placeholder="جميع المسميات" maxLength={60}/></Field><Field label="عدد الأشخاص للبحث والتحقق" hint={'حتى '+(data.provider?.maxCount??50)+' بريدًا موثّقًا؛ قد يعود عدد أقل إذا لم تتوفر إيميلات مؤكدة.'}><input type="number" min="1" max={Math.min(data.provider?.maxCount??50,data.user.balance)} value={filters.count} onChange={e=>change('count',Number(e.target.value))} required/></Field></div></div><div className="form-section confirm-section"><div className="section-label"><span>02</span><h3>راجع ثم ابدأ</h3></div><label className="check-label"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>راجعت المعايير. أوافق على خصم كريدت لكل بريد جديد يتم تسليمه.</span></label>{!data.provider?.configured&&<Notice error>مفتاح FullEnrich غير مضاف بعد. أضفه إلى .env.local وأعد تشغيل المنصة.</Notice>}{error&&<Notice error>{error}</Notice>}<Notice>هذا بحث مدفوع من رصيد FullEnrich: بحث الأشخاص والتحقق من بريد العمل. كريدت المنصة منفصل، ويُخصم للبريد الجديد المحفوظ فقط. لا نطلب هواتف أو إيميلات شخصية.</Notice><div className="search-submit"><span><Coins size={18}/>الحد الأقصى للخصم: <strong>{filters.count||0} كريدت</strong></span><Button type="submit" arrow loading={busy} disabled={!confirmed||!data.user.balance||!data.provider?.configured}>ابدأ البحث الحقيقي</Button></div></div></form></section>
  <aside className="search-aside"><div className="search-summary"><span className="small-icon"><Target size={27} weight="light"/></span><h3>بحثك، في لمحة</h3><div className="summary-line"><Buildings size={18}/><span>{filters.sector}</span></div><div className="summary-line"><MapPin size={18}/><span>{filters.city||filters.country}</span></div><div className="summary-line"><EnvelopeSimple size={18}/><span>حتى {filters.count||0} بريد جديد</span></div><hr/><div className="balance-line"><span>رصيدك الآن</span><strong>{number(data.user.balance)}</strong></div><p>تُخصم النتائج الجديدة فقط. النتائج المكررة أو غير المتاحة لا تستهلك رصيدك.</p></div><div className="help-card"><h4>ابدأ واسعًا، ثم خصّص.</h4><p>إذا لم تجد نتائج، جرّب إزالة المدينة أو المسمى الوظيفي لتوسيع البحث.</p></div><div className="local-note">المصدر FullEnrich. نقبل بريد العمل بحالة DELIVERABLE فقط. البحث داخل قاعدة بيانات المزود؛ لا يضمن نتائج من كل شبكة اجتماعية. القطاعات العامة تُحوّل لأقرب تصنيفات المزود، والتجارة الإلكترونية تشمل متاجر الإنترنت ومنصات الأسواق.</div></aside></div></>;
}

export function LeadsView({data,reload,notify}:ViewProps){
  const query=useSearchParams(),searchId=query.get('search'),search=data.searches.find(s=>s.id===searchId);
  const [text,setText]=useState(''),[sector,setSector]=useState('all'),[sort,setSort]=useState('recent'),[selected,setSelected]=useState<string[]>([]),[page,setPage]=useState(1),[detail,setDetail]=useState<Contact|null>(null),[busy,setBusy]=useState(false);
  const base=searchId?data.contacts.filter(c=>c.search_id===searchId):data.contacts;
  let rows=base.filter(c=>(sector==='all'||c.sector===sector)&&[c.name,c.email,c.company,c.city].join(' ').toLowerCase().includes(text.toLowerCase()));
  if(sort==='name')rows=[...rows].sort((a,b)=>a.name.localeCompare(b.name,'ar'));
  const pages=Math.max(1,Math.ceil(rows.length/10)),activePage=Math.min(page,pages),visible=rows.slice((activePage-1)*10,activePage*10);
  function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
  async function exportRows(){setBusy(true);try{await downloadContacts(selected.length?{ids:selected}:searchId?{searchId}:{});await reload();notify('تم تنزيل الملف دون خصم كريدت إضافي.');}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  return <><PageHeading eyebrow={search?'نتائج البحث':'علاقاتك القادمة'} title={search?search.title:'قائمة العملاء'} description="كل بريد وجدته محفوظ هنا. راجع التفاصيل، ثم جهّز قائمتك للتواصل."><Button variant="secondary" loading={busy} disabled={!base.length} onClick={exportRows}><DownloadSimple size={18}/>{selected.length?'تنزيل المحدد ('+selected.length+')':'تنزيل CSV'}</Button></PageHeading>
  {search?.status==='awaiting_provider'&&<SearchProgress search={search} reload={reload}/>}{search&&['failed','unknown'].includes(search.status)&&<Notice error>{search.message || (search.status==='unknown'?'حالة الطلب غير مؤكدة. راجع سجل FullEnrich قبل إنشاء طلب جديد.':'تعذّر إكمال الطلب. لم يُخصم كريدت لنتائج غير مسلّمة.')}</Notice>}
  {search&&<div className="result-summary"><span><CheckCircle size={21}/><strong>{search.delivered}</strong> بريد جديد</span><span><Coins size={19}/>{search.delivered} كريدت مستخدم</span><span>{search.duplicates} مكرر مستبعد</span><Link href="/leads" className="text-link">عرض قائمتي كاملة <ArrowLeft size={16}/></Link></div>}
  <section className="panel table-panel"><div className="table-toolbar"><div className="search-input"><MagnifyingGlass size={19}/><input aria-label="البحث في جهات الاتصال" placeholder="ابحث بالاسم أو الشركة أو البريد…" value={text} onChange={e=>{setText(e.target.value);setPage(1);}}/></div><select aria-label="تصفية حسب القطاع" value={sector} onChange={e=>{setSector(e.target.value);setPage(1);}}><option value="all">كل القطاعات</option>{[...new Set([...sectors,...data.contacts.map(c=>c.sector).filter(Boolean)])].map(s=><option key={s}>{s}</option>)}</select><select aria-label="ترتيب النتائج" value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">الأحدث أولًا</option><option value="name">حسب الاسم</option></select><span className="result-count">{rows.length} نتيجة</span></div>
  {rows.length?<><div className="table-scroll-hint"><ArrowLeft size={14}/>اسحب الجدول للاطلاع على بقية التفاصيل.</div><div className="table-scroll"><table className="leads-table"><thead><tr><th className="check-cell"><input aria-label="تحديد نتائج الصفحة" type="checkbox" checked={visible.length>0&&visible.every(c=>selected.includes(c.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(c=>c.id)])]:selected.filter(id=>!visible.some(c=>c.id===id)))}/></th><th>جهة الاتصال</th><th>الشركة</th><th>البريد الإلكتروني</th><th>الموقع</th><th>المصدر</th><th/></tr></thead><tbody>{visible.map((c,i)=><tr key={c.id}><td><input aria-label={'تحديد '+c.name} type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/></td><td><button className="contact-name" onClick={()=>setDetail(c)}><span className={'avatar avatar-'+i%4}>{c.name.split(' ').map(s=>s[0]).join('')}</span><span><strong>{c.name}</strong><small>{c.title}</small></span></button></td><td><strong className="company-name">{c.company}</strong><small>{c.sector}</small></td><td><span className="email-text" dir="ltr">{c.email}</span><span className="email-meta"><span/>{c.email_status==='demo'?'عينة تجريبية':'قابل للتسليم وفق FullEnrich'}</span></td><td><span className="location-cell"><MapPin size={14}/>{c.city}</span><small>{c.country}</small></td><td><Badge>{c.email_status==='demo'?'بيانات عرض':'موثّق'}</Badge></td><td><button className="icon-button" title="عرض التفاصيل" aria-label={'تفاصيل '+c.name} onClick={()=>setDetail(c)}><ArrowUpLeft size={19}/></button></td></tr>)}</tbody></table></div><div className="pagination"><span>عرض {(activePage-1)*10+1}–{Math.min(activePage*10,rows.length)} من {rows.length}</span><div><Button variant="ghost" disabled={activePage===1} onClick={()=>setPage(activePage-1)}>السابق</Button><span className="page-number">{activePage}</span><Button variant="ghost" disabled={activePage===pages} onClick={()=>setPage(activePage+1)}>التالي</Button></div></div></>:<Empty title={search?.status==='awaiting_provider'?'بانتظار الإيميلات':search?'لا توجد نتائج جديدة لهذا البحث':'لا توجد نتائج مطابقة'} description={search?.status==='awaiting_provider'?'يمكنك إبقاء الصفحة مفتوحة أو العودة إلى هذا البحث من السجل.':search?'ربما حُفظت النتائج سابقًا، أو أن معايير البحث ضيقة. لم يُخصم كريدت لنتائج غير متاحة.':'جرّب تعديل التصفية أو ابدأ بحثًا جديدًا.'}><Link href="/search" className="button secondary">بحث جديد <MagnifyingGlass size={16}/></Link></Empty>}
  </section><div className="export-tip"><DownloadSimple size={22}/><div><strong>جاهز لخطوتك التالية؟</strong><p>نزّل CSV، ثم ارفعه من صفحة Contacts داخل GoHighLevel وطابق الأعمدة. نتائج FullEnrich تحمل حالة DELIVERABLE، وجهات العرض القديمة موسومة DEMO داخل الملف.</p></div></div>
  {detail&&<Modal title="تفاصيل جهة الاتصال" onClose={()=>setDetail(null)}><div className="contact-detail"><span className="avatar avatar-large">{detail.name[0]}</span><h3>{detail.name}</h3><p>{detail.title} · {detail.company}</p><Badge tone={detail.email_status==='demo'?'amber':'green'}>{detail.email_status==='demo'?'جهة اتصال تجريبية':'بريد عمل · DELIVERABLE'}</Badge><dl><dt>البريد الإلكتروني</dt><dd dir="ltr">{detail.email}<button className="icon-button" aria-label="نسخ البريد" onClick={async()=>{try{await navigator.clipboard.writeText(detail.email);notify('تم نسخ البريد.');}catch{notify('تعذّر النسخ. يمكنك تحديد النص ونسخه.',true);}}}><Copy size={17}/></button></dd><dt>الموقع</dt><dd>{detail.city}، {detail.country}</dd><dt>القطاع</dt><dd>{detail.sector}</dd><dt>حجم الشركة</dt><dd>{detail.size} موظفين</dd><dt>موقع الشركة</dt><dd>{detail.website?<a href={detail.website} target="_blank" rel="noreferrer" className="text-link" dir="ltr">{detail.website} <ArrowSquareOut size={16}/></a>:'غير متاح'}</dd><dt>المصدر</dt><dd>{detail.source}</dd><dt>تاريخ الحفظ</dt><dd>{date(detail.created_at)}</dd></dl></div></Modal>}</>;
}

export function HistoryView({data}:ViewProps){
  return <><PageHeading eyebrow="كل بحث، خطوة للأمام" title="سجل البحث" description="معاييرك السابقة ونتائجها محفوظة لتعود إليها متى أردت."/><section className="panel table-panel">{data.searches.length?<div className="table-scroll"><table><thead><tr><th>البحث</th><th>التاريخ</th><th>الجديد / المطلوب</th><th>المكرر المستبعد</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{data.searches.map(s=><tr key={s.id}><td><strong>{s.title}</strong></td><td>{date(s.created_at)}</td><td>{s.delivered} / {s.requested}</td><td>{s.duplicates}</td><td><Badge tone={s.status==='failed'?'amber':'green'}>{s.status==='failed'?'تعذّر البحث':s.status==='unknown'?'غير مؤكد':s.status==='awaiting_provider'?'بانتظار FullEnrich':s.status==='running'?'جارٍ':s.status==='partial'?'نتائج جزئية':'مكتمل'}</Badge></td><td><div className="row-actions"><Link href={'/leads?search='+s.id} className="text-link">{s.status==='awaiting_provider'?'متابعة الطلب':'النتائج'} <ArrowUpLeft size={15}/></Link><Link href={'/search?from='+s.id} className="icon-button" title="بحث جديد بهذه المعايير"><ClockCounterClockwise size={18}/></Link></div></td></tr>)}</tbody></table></div>:<Empty title="لا توجد عمليات بحث بعد" description="سيظهر هنا كل بحث تجريه مع المعايير والنتائج."/>}</section></>;
}
export function CreditsView({data}:ViewProps){
  const granted=data.ledger.filter(l=>l.amount>0).reduce((a,l)=>a+l.amount,0);
  return <><PageHeading eyebrow="كل كريدت له نتيجة" title="رصيد الكريدت" description="تابع استهلاكك وكل تعديل على رصيدك من مكان واحد."/><div className="credit-overview"><div><Coins size={32} weight="light"/><span>الرصيد المتاح</span><strong>{number(data.user.balance)} <small>كريدت</small></strong></div><div><span>البريد المسلم</span><strong>{data.contacts.length}</strong><p>كريدت واحد لكل بريد جديد.</p></div><div><span>الإضافات في السجل المعروض</span><strong>{number(granted)}</strong><p>يمنح الرصيد ويعدله مالك المنصة.</p></div></div><section className="panel table-panel"><div className="section-title"><h2>حركة الرصيد</h2><Badge>آخر 200 عملية</Badge></div><div className="table-scroll"><table><thead><tr><th>العملية</th><th>التفاصيل</th><th>التاريخ</th><th>التغيير</th><th>الرصيد بعدها</th></tr></thead><tbody>{data.ledger.map(l=><tr key={l.id}><td><span className={'ledger-icon '+(l.amount<0?'debit':'')}><ArrowDown size={16}/></span>{l.kind==='debit'?'تسليم بريد':l.kind==='grant'?'إضافة رصيد':'تصحيح الرصيد'}</td><td>{l.reason}</td><td>{date(l.created_at)}</td><td><span className={l.amount>=0?'positive':''} dir="ltr">{l.amount>0?'+':''}{l.amount}</span></td><td>{number(l.balance_after)}</td></tr>)}</tbody></table></div></section></>;
}
export function SettingsView({data,reload,notify}:ViewProps){
  const [name,setName]=useState(data.user.name),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('profile',{name});await reload();notify('تم حفظ بيانات حسابك.');}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  async function change(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('password',{current,password});setCurrent('');setPassword('');notify('تم تغيير كلمة المرور وإنهاء الجلسات السابقة.');}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}
  return <><PageHeading eyebrow="مساحتك الشخصية" title="إعدادات الحساب" description="بيانات حسابك وإعدادات الوصول."/><div className="settings-grid"><section className="panel"><h2>الملف الشخصي</h2><form className="form-stack" onSubmit={save}><Field label="الاسم"><input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={60} required/></Field><Field label="البريد الإلكتروني"><input dir="ltr" value={data.user.email} disabled/></Field><Button loading={busy} type="submit">حفظ التغييرات <Check size={18}/></Button></form></section><section className="panel"><h2>تغيير كلمة المرور</h2><form className="form-stack" onSubmit={change}><Field label="كلمة المرور الحالية"><input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} required/></Field><Field label="كلمة المرور الجديدة" hint="10 أحرف على الأقل."><input type="password" autoComplete="new-password" minLength={10} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required/></Field><Button variant="secondary" loading={busy} type="submit">تحديث كلمة المرور</Button></form></section></div><Notice>حسابات العرض تدخل من أزرار التجربة. يمكنك إنشاء حساب بدعوة من لوحة الأونر لتجربة كلمة مرور تختارها بنفسك.</Notice></>;
}
